
def matches():
    return [
        {'date': '2014-06-12', 'team1': 'Brazil', 'team2': 'Croatia', 'gd': 2, 'match': 'A1', 'group': 'A'},
        {'date': '2014-06-13', 'team1': 'Chile', 'team2': 'Australia', 'gd': 2, 'match': 'B1', 'group': 'B'},
        {'date': '2014-06-13', 'team1': 'Mexico', 'team2': 'Cameroon', 'gd': 1, 'match': 'A2', 'group': 'A'},
        {'date': '2014-06-13', 'team1': 'Spain', 'team2': 'Netherlands', 'gd': -4, 'match': 'B2', 'group': 'B'},
        {'date': '2014-06-14', 'team1': 'Colombia', 'team2': 'Greece', 'gd': 3, 'match': 'C1', 'group': 'C'},
        {'date': '2014-06-14', 'team1': 'England', 'team2': 'Italy', 'gd': -1, 'match': 'D1', 'group': 'D'},
        {'date': '2014-06-14', 'team1': 'Ivory Coast', 'team2': 'Japan', 'gd': 1, 'match': 'C2', 'group': 'C'},
        {'date': '2014-06-14', 'team1': 'Uruguay', 'team2': 'Costa Rica', 'gd': -2, 'match': 'D2', 'group': 'D'},
        {'date': '2014-06-15', 'team1': 'Argentina', 'team2': 'Bosnia-Herzegovina', 'gd': 1, 'match': 'F1',
         'group': 'F'},
        {'date': '2014-06-15', 'team1': 'France', 'team2': 'Honduras', 'gd': 3, 'match': 'E1', 'group': 'E'},
        {'date': '2014-06-15', 'team1': 'Switzerland', 'team2': 'Ecuador', 'gd': 1, 'match': 'E2', 'group': 'E'},
        {'date': '2014-06-16', 'team1': 'Germany', 'team2': 'Portugal', 'gd': 4, 'match': 'G1', 'group': 'G'},
        {'date': '2014-06-16', 'team1': 'Ghana', 'team2': 'USA', 'gd': -1, 'match': 'G2', 'group': 'G'},
        {'date': '2014-06-16', 'team1': 'Iran', 'team2': 'Nigeria', 'gd': 0, 'match': 'F2', 'group': 'F'},
        {'date': '2014-06-17', 'team1': 'Belgium', 'team2': 'Algeria', 'gd': 1, 'match': 'H1', 'group': 'H'},
        {'date': '2014-06-17', 'team1': 'Brazil', 'team2': 'Mexico', 'gd': 0, 'match': 'A3', 'group': 'A'},
        {'date': '2014-06-17', 'team1': 'Russia', 'team2': 'Korea Republic', 'gd': 0, 'match': 'H2', 'group': 'H'},
        {'date': '2014-06-18', 'team1': 'Australia', 'team2': 'Netherlands', 'gd': -1, 'match': 'B3', 'group': 'B'},
        {'date': '2014-06-18', 'team1': 'Cameroon', 'team2': 'Croatia', 'gd': -4, 'match': 'A4', 'group': 'A'},
        {'date': '2014-06-18', 'team1': 'Spain', 'team2': 'Chile', 'gd': -2, 'match': 'B4', 'group': 'B'},
        {'date': '2014-06-19', 'team1': 'Colombia', 'team2': 'Ivory Coast', 'gd': 1, 'match': 'C3', 'group': 'C'},
        {'date': '2014-06-19', 'team1': 'Japan', 'team2': 'Greece', 'gd': 0, 'match': 'C4', 'group': 'C'},
        {'date': '2014-06-19', 'team1': 'Uruguay', 'team2': 'England', 'gd': 1, 'match': 'D3', 'group': 'D'},
        {'date': '2014-06-20', 'team1': 'Honduras', 'team2': 'Ecuador', 'gd': -1, 'match': 'E3', 'group': 'E'},
        {'date': '2014-06-20', 'team1': 'Italy', 'team2': 'Costa Rica', 'gd': -1, 'match': 'D4', 'group': 'D'},
        {'date': '2014-06-20', 'team1': 'Switzerland', 'team2': 'France', 'gd': -3, 'match': 'E4', 'group': 'E'},
        {'date': '2014-06-21', 'team1': 'Argentina', 'team2': 'Iran', 'gd': 1, 'match': 'F3', 'group': 'F'},
        {'date': '2014-06-21', 'team1': 'Germany', 'team2': 'Ghana', 'gd': 0, 'match': 'G3', 'group': 'G'},
        {'date': '2014-06-21', 'team1': 'Nigeria', 'team2': 'Bosnia-Herzegovina', 'gd': 1, 'match': 'F4', 'group': 'F'},
        {'date': '2014-06-22', 'team1': 'Belgium', 'team2': 'Russia', 'gd': 1, 'match': 'H3', 'group': 'H'},
        {'date': '2014-06-22', 'team1': 'Korea Republic', 'team2': 'Algeria', 'gd': -2, 'match': 'H4', 'group': 'H'},
        {'date': '2014-06-22', 'team1': 'USA', 'team2': 'Portugal', 'gd': 0, 'match': 'G4', 'group': 'G'},
        {'date': '2014-06-23', 'team1': 'Australia', 'team2': 'Spain', 'gd': -3, 'match': 'B5', 'group': 'B'},
        {'date': '2014-06-23', 'team1': 'Cameroon', 'team2': 'Brazil', 'gd': -3, 'match': 'A5', 'group': 'A'},
        {'date': '2014-06-23', 'team1': 'Croatia', 'team2': 'Mexico', 'gd': -2, 'match': 'A6', 'group': 'A'},
        {'date': '2014-06-23', 'team1': 'Netherlands', 'team2': 'Chile', 'gd': 2, 'match': 'B6', 'group': 'B'},
        {'date': '2014-06-24', 'team1': 'Costa Rica', 'team2': 'England', 'gd': 0, 'match': 'D5', 'group': 'D'},
        {'date': '2014-06-24', 'team1': 'Greece', 'team2': 'Ivory Coast', 'gd': 1, 'match': 'C5', 'group': 'C'},
        {'date': '2014-06-24', 'team1': 'Italy', 'team2': 'Uruguay', 'gd': -1, 'match': 'D6', 'group': 'D'},
        {'date': '2014-06-24', 'team1': 'Japan', 'team2': 'Colombia', 'gd': -3, 'match': 'C6', 'group': 'C'},
        {'date': '2014-06-25', 'team1': 'Bosnia-Herzegovina', 'team2': 'Iran', 'gd': 2, 'match': 'F5', 'group': 'F'},
        {'date': '2014-06-25', 'team1': 'Ecuador', 'team2': 'France', 'gd': 0, 'match': 'E5', 'group': 'E'},
        {'date': '2014-06-25', 'team1': 'Honduras', 'team2': 'Switzerland', 'gd': -3, 'match': 'E6', 'group': 'E'},
        {'date': '2014-06-25', 'team1': 'Nigeria', 'team2': 'Argentina', 'gd': -1, 'match': 'F6', 'group': 'F'},
        {'date': '2014-06-26', 'team1': 'Algeria', 'team2': 'Russia', 'gd': 0, 'match': 'H5', 'group': 'H'},
        {'date': '2014-06-26', 'team1': 'Korea Republic', 'team2': 'Belgium', 'gd': -1, 'match': 'H6', 'group': 'H'},
        {'date': '2014-06-26', 'team1': 'Portugal', 'team2': 'Ghana', 'gd': 1, 'match': 'G5', 'group': 'G'},
        {'date': '2014-06-26', 'team1': 'USA', 'team2': 'Germany', 'gd': -1, 'match': 'G6', 'group': 'G'},
        {'date': '2014-06-28', 'team1': 'Brazil', 'team2': 'Chile', 'gd': 0, 'match': '8AB', 'group': ''},
        {'date': '2014-06-28', 'team1': 'Colombia', 'team2': 'Uruguay', 'gd': 2, 'match': '8CD', 'group': ''},
        {'date': '2014-06-29', 'team1': 'Costa Rica', 'team2': 'Greece', 'gd': 0, 'match': '8DC', 'group': ''},
        {'date': '2014-06-29', 'team1': 'Netherlands', 'team2': 'Mexico', 'gd': 1, 'match': '8BA', 'group': ''},
        {'date': '2014-06-30', 'team1': 'France', 'team2': 'Nigeria', 'gd': 2, 'match': '8EF', 'group': ''},
        {'date': '2014-06-30', 'team1': 'Germany', 'team2': 'Algeria', 'gd': 1, 'match': '8GH', 'group': ''},
        {'date': '2014-07-01', 'team1': 'Argentina', 'team2': 'Switzerland', 'gd': 1, 'match': '8FE', 'group': ''},
        {'date': '2014-07-01', 'team1': 'Belgium', 'team2': 'USA', 'gd': 1, 'match': '8HG', 'group': ''},
        {'date': '2014-07-04', 'team1': 'Brazil', 'team2': 'Colombia', 'gd': 1, 'match': '4ABCD', 'group': ''},
        {'date': '2014-07-04', 'team1': 'France', 'team2': 'Germany', 'gd': -1, 'match': '4DCBA', 'group': ''},
        {'date': '2014-07-05', 'team1': 'Argentina', 'team2': 'Belgium', 'gd': 1, 'match': '4FEHG', 'group': ''},
        {'date': '2014-07-05', 'team1': 'Netherlands', 'team2': 'Costa Rica', 'gd': 0, 'match': '4EFGH', 'group': ''},
        {'date': '2014-07-08', 'team1': 'Brazil', 'team2': 'Germany', 'gd': -6, 'match': '2ABCDDCBA', 'group': ''},
        {'date': '2014-07-09', 'team1': 'Netherlands', 'team2': 'Argentina', 'gd': 0, 'match': '2EFGHFEHG', 'group': ''},
        {'date': '2014-07-12', 'team1': 'Brazil', 'team2': 'Netherlands', 'gd': -3, 'match': '1M', 'group': ''},
        {'date': '2014-07-13', 'team1': 'Germany', 'team2': 'Argentina', 'gd': 1, 'match': '1', 'group': ''},
    ]


def match_codes():
    return [r['match'] for r in matches()]

def teams():
    t = set(r['team1'] for r in matches())  | set(r['team2'] for r in matches())
    return sorted(list(t))

def results():
    return {r['match']:  r['gd'] for r in matches()}

def groups():
    group_names = set(r['group'] for r in matches() if r['group'] != '')
    groups = {g:set() for g in group_names}
    for r in matches():
        if r['group'] != '':
            groups[r['group']].add(r['team1'])
            groups[r['group']].add(r['team2'])
    return groups


def qualification_teams():
    t = set(r['team1'] for r in matches())  | set(r['team2'] for r in qualifications())
    return sorted(list(t))

def qualifications():
    return [
        {'team1': 'Montserrat', 'team2': 'Belize', 'gd': -3},
        {'team1': 'Afghanistan', 'team2': 'Palestine', 'gd': -2},
        {'team1': 'Bangladesh', 'team2': 'Pakistan', 'gd': 3},
        {'team1': 'Cambodia', 'team2': 'Laos', 'gd': 2},
        {'team1': 'Malaysia', 'team2': 'Taiwan', 'gd': 1},
        {'team1': 'Mongolia', 'team2': 'Burma', 'gd': 1},
        {'team1': 'Nepal', 'team2': 'East Timor', 'gd': 1},
        {'team1': 'Sri Lanka', 'team2': 'Philippines', 'gd': 0},
        {'team1': 'Vietnam', 'team2': 'Macau', 'gd': 6},
        {'team1': 'East Timor', 'team2': 'Nepal', 'gd': -5},
        {'team1': 'Turks and Caicos Islands', 'team2': 'Bahamas', 'gd': -4},
        {'team1': 'Burma', 'team2': 'Mongolia', 'gd': 2},
        {'team1': 'Laos', 'team2': 'Cambodia', 'gd': 4},
        {'team1': 'Macau', 'team2': 'Vietnam', 'gd': -6},
        {'team1': 'Pakistan', 'team2': 'Bangladesh', 'gd': 0},
        {'team1': 'Palestine', 'team2': 'Afghanistan', 'gd': 0},
        {'team1': 'Philippines', 'team2': 'Sri Lanka', 'gd': 4},
        {'team1': 'Virgin Islands', 'team2': 'British Virgin Islands', 'gd': 2},
        {'team1': 'Anguilla', 'team2': 'Dominican Republic', 'gd': -2},
        {'team1': 'Aruba', 'team2': 'St Lucia', 'gd': 2},
        {'team1': 'Bahamas', 'team2': 'Turks and Caicos Islands', 'gd': 6},
        {'team1': 'British Virgin Islands', 'team2': 'Virgin Islands', 'gd': -1},
        {'team1': 'Dominican Republic', 'team2': 'Anguilla', 'gd': 4},
        {'team1': 'St Lucia', 'team2': 'Aruba', 'gd': 2},
        {'team1': 'Belize', 'team2': 'Montserrat', 'gd': 2},
        {'team1': 'China', 'team2': 'Laos', 'gd': 5},
        {'team1': 'Iran', 'team2': 'Maldives', 'gd': 4},
        {'team1': 'Iraq', 'team2': 'Yemen', 'gd': 2},
        {'team1': 'Jordan', 'team2': 'Nepal', 'gd': 9},
        {'team1': 'Kuwait', 'team2': 'Philippines', 'gd': 3},
        {'team1': 'Lebanon', 'team2': 'Bangladesh', 'gd': 4},
        {'team1': 'Oman', 'team2': 'Burma', 'gd': 2},
        {'team1': 'Qatar', 'team2': 'Vietnam', 'gd': 3},
        {'team1': 'Saudi Arabia', 'team2': 'Hong Kong', 'gd': 3},
        {'team1': 'Singapore', 'team2': 'Malaysia', 'gd': 2},
        {'team1': 'Syria', 'team2': 'Tajikistan', 'gd': -3},
        {'team1': 'Thailand', 'team2': 'Palestine', 'gd': 1},
        {'team1': 'Turkmenistan', 'team2': 'Indonesia', 'gd': 0},
        {'team1': 'United Arab Emirates', 'team2': 'India', 'gd': 3},
        {'team1': 'Uzbekistan', 'team2': 'Kyrgyzstan', 'gd': 4},
        {'team1': 'Bangladesh', 'team2': 'Lebanon', 'gd': 2},
        {'team1': 'Burma', 'team2': 'Oman', 'gd': -2},
        {'team1': 'Hong Kong', 'team2': 'Saudi Arabia', 'gd': -5},
        {'team1': 'India', 'team2': 'United Arab Emirates', 'gd': 0},
        {'team1': 'Indonesia', 'team2': 'Turkmenistan', 'gd': 1},
        {'team1': 'Kyrgyzstan', 'team2': 'Uzbekistan', 'gd': -3},
        {'team1': 'Laos', 'team2': 'China', 'gd': -5},
        {'team1': 'Malaysia', 'team2': 'Singapore', 'gd': 0},
        {'team1': 'Maldives', 'team2': 'Iran', 'gd': -1},
        {'team1': 'Nepal', 'team2': 'Jordan', 'gd': 0},
        {'team1': 'Palestine', 'team2': 'Thailand', 'gd': 0},
        {'team1': 'Philippines', 'team2': 'Kuwait', 'gd': -1},
        {'team1': 'Tajikistan', 'team2': 'Syria', 'gd': 3},
        {'team1': 'Vietnam', 'team2': 'Qatar', 'gd': 1},
        {'team1': 'Yemen', 'team2': 'Iraq', 'gd': 0},
        {'team1': 'Antigua and Barbuda', 'team2': 'CuraÃ§ao', 'gd': 3},
        {'team1': 'Australia', 'team2': 'Thailand', 'gd': 1},
        {'team1': 'Bahrain', 'team2': 'Qatar', 'gd': 0},
        {'team1': 'Canada', 'team2': 'St Lucia', 'gd': 3},
        {'team1': 'China', 'team2': 'Singapore', 'gd': 1},
        {'team1': 'Dominica', 'team2': 'Nicaragua', 'gd': -2},
        {'team1': 'El Salvador', 'team2': 'Dominican Republic', 'gd': 1},
        {'team1': 'Grenada', 'team2': 'Belize', 'gd': -3},
        {'team1': 'Guyana', 'team2': 'Barbados', 'gd': 2},
        {'team1': 'Haiti', 'team2': 'Virgin Islands', 'gd': 6},
        {'team1': 'Iran', 'team2': 'Indonesia', 'gd': 3},
        {'team1': 'Iraq', 'team2': 'Jordan', 'gd': -2},
        {'team1': 'Japan', 'team2': 'Korea DPR', 'gd': 1},
        {'team1': 'Korea Republic', 'team2': 'Lebanon', 'gd': 6},
        {'team1': 'Oman', 'team2': 'Saudi Arabia', 'gd': 0},
        {'team1': 'St Kitts and Nevis', 'team2': 'Puerto Rico', 'gd': 0},
        {'team1': 'Suriname', 'team2': 'Cayman Islands', 'gd': 1},
        {'team1': 'Tajikistan', 'team2': 'Uzbekistan', 'gd': -1},
        {'team1': 'Trinidad and Tobago', 'team2': 'Bermuda', 'gd': 1},
        {'team1': 'United Arab Emirates', 'team2': 'Kuwait', 'gd': -1},
        {'team1': 'Barbados', 'team2': 'Trinidad and Tobago', 'gd': -2},
        {'team1': 'Belize', 'team2': 'Guatemala', 'gd': -1},
        {'team1': 'Cayman Islands', 'team2': 'El Salvador', 'gd': -3},
        {'team1': 'CuraÃ§ao', 'team2': 'Haiti', 'gd': -2},
        {'team1': 'Dominican Republic', 'team2': 'Suriname', 'gd': 0},
        {'team1': 'Guyana', 'team2': 'Bermuda', 'gd': 1},
        {'team1': 'Indonesia', 'team2': 'Bahrain', 'gd': -2},
        {'team1': 'Jordan', 'team2': 'China', 'gd': 1},
        {'team1': 'Korea DPR', 'team2': 'Tajikistan', 'gd': 1},
        {'team1': 'Kuwait', 'team2': 'Korea Republic', 'gd': 0},
        {'team1': 'Lebanon', 'team2': 'United Arab Emirates', 'gd': 2},
        {'team1': 'Nicaragua', 'team2': 'Panama', 'gd': -1},
        {'team1': 'Puerto Rico', 'team2': 'Canada', 'gd': -3},
        {'team1': 'Qatar', 'team2': 'Iran', 'gd': 0},
        {'team1': 'Saudi Arabia', 'team2': 'Australia', 'gd': -2},
        {'team1': 'Singapore', 'team2': 'Iraq', 'gd': -2},
        {'team1': 'St Lucia', 'team2': 'St Kitts and Nevis', 'gd': -2},
        {'team1': 'Thailand', 'team2': 'Oman', 'gd': 3},
        {'team1': 'Uzbekistan', 'team2': 'Japan', 'gd': 0},
        {'team1': 'Virgin Islands', 'team2': 'Antigua and Barbuda', 'gd': -7},
        {'team1': 'Argentina', 'team2': 'Chile', 'gd': 3},
        {'team1': 'Barbados', 'team2': 'Guyana', 'gd': -2},
        {'team1': 'Belize', 'team2': 'Grenada', 'gd': -3},
        {'team1': 'Bermuda', 'team2': 'Trinidad and Tobago', 'gd': 1},
        {'team1': 'Cayman Islands', 'team2': 'Suriname', 'gd': -1},
        {'team1': 'CuraÃ§ao', 'team2': 'Antigua and Barbuda', 'gd': -1},
        {'team1': 'Dominica', 'team2': 'Panama', 'gd': -5},
        {'team1': 'Dominican Republic', 'team2': 'El Salvador', 'gd': -1},
        {'team1': 'Ecuador', 'team2': 'Venezuela', 'gd': 2},
        {'team1': 'Peru', 'team2': 'Paraguay', 'gd': 2},
        {'team1': 'Puerto Rico', 'team2': 'St Kitts and Nevis', 'gd': 0},
        {'team1': 'St Lucia', 'team2': 'Canada', 'gd': -7},
        {'team1': 'Uruguay', 'team2': 'Bolivia', 'gd': 2},
        {'team1': 'Virgin Islands', 'team2': 'Haiti', 'gd': -7},
        {'team1': 'Antigua and Barbuda', 'team2': 'Virgin Islands', 'gd': 10},
        {'team1': 'Australia', 'team2': 'Oman', 'gd': 3},
        {'team1': 'Bermuda', 'team2': 'Guyana', 'gd': 0},
        {'team1': 'Bolivia', 'team2': 'Colombia', 'gd': -1},
        {'team1': 'Canada', 'team2': 'Puerto Rico', 'gd': 0},
        {'team1': 'Chile', 'team2': 'Peru', 'gd': 2},
        {'team1': 'China', 'team2': 'Iraq', 'gd': -1},
        {'team1': 'El Salvador', 'team2': 'Cayman Islands', 'gd': 4},
        {'team1': 'Guatemala', 'team2': 'Belize', 'gd': 2},
        {'team1': 'Haiti', 'team2': 'CuraÃ§ao', 'gd': 0},
        {'team1': 'Indonesia', 'team2': 'Qatar', 'gd': -1},
        {'team1': 'Iran', 'team2': 'Bahrain', 'gd': 6},
        {'team1': 'Japan', 'team2': 'Tajikistan', 'gd': 8},
        {'team1': 'Korea DPR', 'team2': 'Uzbekistan', 'gd': -1},
        {'team1': 'Korea Republic', 'team2': 'United Arab Emirates', 'gd': 1},
        {'team1': 'Lebanon', 'team2': 'Kuwait', 'gd': 0},
        {'team1': 'Panama', 'team2': 'Nicaragua', 'gd': 4},
        {'team1': 'Paraguay', 'team2': 'Uruguay', 'gd': 0},
        {'team1': 'Singapore', 'team2': 'Jordan', 'gd': -3},
        {'team1': 'St Kitts and Nevis', 'team2': 'St Lucia', 'gd': 0},
        {'team1': 'Suriname', 'team2': 'Dominican Republic', 'gd': -2},
        {'team1': 'Thailand', 'team2': 'Saudi Arabia', 'gd': 0},
        {'team1': 'Trinidad and Tobago', 'team2': 'Barbados', 'gd': 4},
        {'team1': 'Venezuela', 'team2': 'Argentina', 'gd': 1},
        {'team1': 'Antigua and Barbuda', 'team2': 'Haiti', 'gd': 1},
        {'team1': 'Argentina', 'team2': 'Bolivia', 'gd': 0},
        {'team1': 'Bahrain', 'team2': 'Iran', 'gd': 0},
        {'team1': 'Bermuda', 'team2': 'Barbados', 'gd': 1},
        {'team1': 'Chad', 'team2': 'Tanzania', 'gd': -1},
        {'team1': 'Colombia', 'team2': 'Venezuela', 'gd': 0},
        {'team1': 'Comoros', 'team2': 'Mozambique', 'gd': -1},
        {'team1': 'Djibouti', 'team2': 'Namibia', 'gd': -4},
        {'team1': 'Dominican Republic', 'team2': 'Cayman Islands', 'gd': 4},
        {'team1': 'Equatorial Guinea', 'team2': 'Madagascar', 'gd': 2},
        {'team1': 'Eritrea', 'team2': 'Rwanda', 'gd': 0},
        {'team1': 'Guatemala', 'team2': 'Grenada', 'gd': 3},
        {'team1': 'Guinea-Bissau', 'team2': 'Togo', 'gd': 0},
        {'team1': 'Guyana', 'team2': 'Trinidad and Tobago', 'gd': 1},
        {'team1': 'Iraq', 'team2': 'China', 'gd': 1},
        {'team1': 'Jordan', 'team2': 'Singapore', 'gd': 2},
        {'team1': 'Kuwait', 'team2': 'Lebanon', 'gd': -1},
        {'team1': 'Lesotho', 'team2': 'Burundi', 'gd': 1},
        {'team1': 'Nicaragua', 'team2': 'Dominica', 'gd': 1},
        {'team1': 'Oman', 'team2': 'Australia', 'gd': 1},
        {'team1': 'Paraguay', 'team2': 'Ecuador', 'gd': 1},
        {'team1': 'Qatar', 'team2': 'Indonesia', 'gd': 4},
        {'team1': 'SÃ£o TomÃ© and PrÃ­ncipe', 'team2': 'Congo', 'gd': -5},
        {'team1': 'Saudi Arabia', 'team2': 'Thailand', 'gd': 3},
        {'team1': 'Seychelles', 'team2': 'Kenya', 'gd': -3},
        {'team1': 'St Kitts and Nevis', 'team2': 'Canada', 'gd': 0},
        {'team1': 'St Lucia', 'team2': 'Puerto Rico', 'gd': -4},
        {'team1': 'Suriname', 'team2': 'El Salvador', 'gd': -2},
        {'team1': 'Swaziland', 'team2': 'Congo DR', 'gd': -2},
        {'team1': 'Tajikistan', 'team2': 'Japan', 'gd': -4},
        {'team1': 'United Arab Emirates', 'team2': 'Korea Republic', 'gd': -2},
        {'team1': 'Uruguay', 'team2': 'Chile', 'gd': 4},
        {'team1': 'Uzbekistan', 'team2': 'Korea DPR', 'gd': 1},
        {'team1': 'Virgin Islands', 'team2': 'CuraÃ§ao', 'gd': -3},
        {'team1': 'Somalia', 'team2': 'Ethiopia', 'gd': 0},
        {'team1': 'Barbados', 'team2': 'Bermuda', 'gd': -1},
        {'team1': 'Cayman Islands', 'team2': 'Dominican Republic', 'gd': 0},
        {'team1': 'Puerto Rico', 'team2': 'St Lucia', 'gd': 3},
        {'team1': 'Burundi', 'team2': 'Lesotho', 'gd': 0},
        {'team1': 'Canada', 'team2': 'St Kitts and Nevis', 'gd': 4},
        {'team1': 'Chile', 'team2': 'Paraguay', 'gd': 2},
        {'team1': 'Colombia', 'team2': 'Argentina', 'gd': -1},
        {'team1': 'Congo', 'team2': 'SÃ£o TomÃ© and PrÃ­ncipe', 'gd': 0},
        {'team1': 'Congo DR', 'team2': 'Swaziland', 'gd': 4},
        {'team1': 'CuraÃ§ao', 'team2': 'Virgin Islands', 'gd': 5},
        {'team1': 'Ecuador', 'team2': 'Peru', 'gd': 2},
        {'team1': 'El Salvador', 'team2': 'Suriname', 'gd': 4},
        {'team1': 'Grenada', 'team2': 'Guatemala', 'gd': -3},
        {'team1': 'Haiti', 'team2': 'Antigua and Barbuda', 'gd': 1},
        {'team1': 'Indonesia', 'team2': 'Iran', 'gd': -3},
        {'team1': 'Jordan', 'team2': 'Iraq', 'gd': -2},
        {'team1': 'Kenya', 'team2': 'Seychelles', 'gd': 4},
        {'team1': 'Korea DPR', 'team2': 'Japan', 'gd': 1},
        {'team1': 'Kuwait', 'team2': 'United Arab Emirates', 'gd': 1},
        {'team1': 'Lebanon', 'team2': 'Korea Republic', 'gd': 1},
        {'team1': 'Madagascar', 'team2': 'Equatorial Guinea', 'gd': 1},
        {'team1': 'Mozambique', 'team2': 'Comoros', 'gd': 3},
        {'team1': 'Namibia', 'team2': 'Djibouti', 'gd': 4},
        {'team1': 'Panama', 'team2': 'Dominica', 'gd': 3},
        {'team1': 'Qatar', 'team2': 'Bahrain', 'gd': 0},
        {'team1': 'Rwanda', 'team2': 'Eritrea', 'gd': 2},
        {'team1': 'Saudi Arabia', 'team2': 'Oman', 'gd': 0},
        {'team1': 'Singapore', 'team2': 'China', 'gd': -4},
        {'team1': 'Tanzania', 'team2': 'Chad', 'gd': -1},
        {'team1': 'Thailand', 'team2': 'Australia', 'gd': -1},
        {'team1': 'Togo', 'team2': 'Guinea-Bissau', 'gd': 1},
        {'team1': 'Trinidad and Tobago', 'team2': 'Guyana', 'gd': 2},
        {'team1': 'Uzbekistan', 'team2': 'Tajikistan', 'gd': 3},
        {'team1': 'Venezuela', 'team2': 'Bolivia', 'gd': 1},
        {'team1': 'Ethiopia', 'team2': 'Somalia', 'gd': 5},
        {'team1': 'Australia', 'team2': 'Saudi Arabia', 'gd': 2},
        {'team1': 'Bahrain', 'team2': 'Indonesia', 'gd': 10},
        {'team1': 'China', 'team2': 'Jordan', 'gd': 2},
        {'team1': 'Iran', 'team2': 'Qatar', 'gd': 0},
        {'team1': 'Iraq', 'team2': 'Singapore', 'gd': 6},
        {'team1': 'Japan', 'team2': 'Uzbekistan', 'gd': -1},
        {'team1': 'Korea Republic', 'team2': 'Kuwait', 'gd': 2},
        {'team1': 'Oman', 'team2': 'Thailand', 'gd': 2},
        {'team1': 'Tajikistan', 'team2': 'Korea DPR', 'gd': 0},
        {'team1': 'United Arab Emirates', 'team2': 'Lebanon', 'gd': 2},
        {'team1': 'Egypt', 'team2': 'Mozambique', 'gd': 2},
        {'team1': 'Ghana', 'team2': 'Lesotho', 'gd': 7},
        {'team1': 'Algeria', 'team2': 'Rwanda', 'gd': 4},
        {'team1': 'Argentina', 'team2': 'Ecuador', 'gd': 4},
        {'team1': 'Bolivia', 'team2': 'Chile', 'gd': -2},
        {'team1': 'Burkina Faso', 'team2': 'Congo', 'gd': -3},
        {'team1': 'Cameroon', 'team2': 'Congo DR', 'gd': 1},
        {'team1': 'Central African Republic', 'team2': 'Botswana', 'gd': 2},
        {'team1': 'Gambia', 'team2': 'Morocco', 'gd': 0},
        {'team1': 'Ivory Coast', 'team2': 'Tanzania', 'gd': 2},
        {'team1': 'Kenya', 'team2': 'Malawi', 'gd': 0},
        {'team1': 'Senegal', 'team2': 'Liberia', 'gd': 2},
        {'team1': 'Sierra Leone', 'team2': 'Cape Verde', 'gd': 1},
        {'team1': 'Sudan', 'team2': 'Zambia', 'gd': -3},
        {'team1': 'Tunisia', 'team2': 'Equatorial Guinea', 'gd': 2},
        {'team1': 'Uruguay', 'team2': 'Venezuela', 'gd': 0},
        {'team1': 'Angola', 'team2': 'Uganda', 'gd': 0},
        {'team1': 'Benin', 'team2': 'Mali', 'gd': 1},
        {'team1': 'Japan', 'team2': 'Oman', 'gd': 3},
        {'team1': 'Jordan', 'team2': 'Iraq', 'gd': 0},
        {'team1': 'Lebanon', 'team2': 'Qatar', 'gd': -1},
        {'team1': 'Niger', 'team2': 'Gabon', 'gd': 3},
        {'team1': 'Nigeria', 'team2': 'Namibia', 'gd': 1},
        {'team1': 'Peru', 'team2': 'Colombia', 'gd': -1},
        {'team1': 'South Africa', 'team2': 'Ethiopia', 'gd': 0},
        {'team1': 'Togo', 'team2': 'Libya', 'gd': 0},
        {'team1': 'Uzbekistan', 'team2': 'Iran', 'gd': -1},
        {'team1': 'Zimbabwe', 'team2': 'Guinea', 'gd': -1},
        {'team1': 'Costa Rica', 'team2': 'El Salvador', 'gd': 0},
        {'team1': 'Cuba', 'team2': 'Canada', 'gd': -1},
        {'team1': 'Honduras', 'team2': 'Panama', 'gd': -2},
        {'team1': 'Jamaica', 'team2': 'Guatemala', 'gd': 1},
        {'team1': 'Japan', 'team2': 'Jordan', 'gd': 6},
        {'team1': 'Lebanon', 'team2': 'Uzbekistan', 'gd': 0},
        {'team1': 'Mexico', 'team2': 'Guyana', 'gd': 2},
        {'team1': 'Oman', 'team2': 'Australia', 'gd': 0},
        {'team1': 'Qatar', 'team2': 'Korea Republic', 'gd': -3},
        {'team1': 'USA', 'team2': 'Antigua and Barbuda', 'gd': 2},
        {'team1': 'Bolivia', 'team2': 'Paraguay', 'gd': 2},
        {'team1': 'Botswana', 'team2': 'South Africa', 'gd': 0},
        {'team1': 'Cape Verde', 'team2': 'Tunisia', 'gd': -1},
        {'team1': 'Congo', 'team2': 'Niger', 'gd': 1},
        {'team1': 'Equatorial Guinea', 'team2': 'Sierra Leone', 'gd': 0},
        {'team1': 'Gabon', 'team2': 'Burkina Faso', 'gd': 1},
        {'team1': 'Malawi', 'team2': 'Nigeria', 'gd': 0},
        {'team1': 'Morocco', 'team2': 'Ivory Coast', 'gd': 0},
        {'team1': 'Namibia', 'team2': 'Kenya', 'gd': 1},
        {'team1': 'Uganda', 'team2': 'Senegal', 'gd': 0},
        {'team1': 'Venezuela', 'team2': 'Chile', 'gd': -2},
        {'team1': 'Zambia', 'team2': 'Ghana', 'gd': 1},
        {'team1': 'Congo DR', 'team2': 'Togo', 'gd': 2},
        {'team1': 'Ecuador', 'team2': 'Colombia', 'gd': 1},
        {'team1': 'Ethiopia', 'team2': 'Central African Republic', 'gd': 2},
        {'team1': 'Guinea', 'team2': 'Egypt', 'gd': -1},
        {'team1': 'Lesotho', 'team2': 'Sudan', 'gd': 0},
        {'team1': 'Liberia', 'team2': 'Angola', 'gd': 0},
        {'team1': 'Libya', 'team2': 'Cameroon', 'gd': 1},
        {'team1': 'Mali', 'team2': 'Algeria', 'gd': 1},
        {'team1': 'Mozambique', 'team2': 'Zimbabwe', 'gd': 0},
        {'team1': 'Rwanda', 'team2': 'Benin', 'gd': 0},
        {'team1': 'Tanzania', 'team2': 'Gambia', 'gd': 1},
        {'team1': 'Uruguay', 'team2': 'Peru', 'gd': 2},
        {'team1': 'Antigua and Barbuda', 'team2': 'Jamaica', 'gd': 0},
        {'team1': 'Australia', 'team2': 'Japan', 'gd': 0},
        {'team1': 'Canada', 'team2': 'Honduras', 'gd': 0},
        {'team1': 'El Salvador', 'team2': 'Mexico', 'gd': -1},
        {'team1': 'Guatemala', 'team2': 'USA', 'gd': 0},
        {'team1': 'Guyana', 'team2': 'Costa Rica', 'gd': -4},
        {'team1': 'Iran', 'team2': 'Qatar', 'gd': 0},
        {'team1': 'Iraq', 'team2': 'Oman', 'gd': 0},
        {'team1': 'Korea Republic', 'team2': 'Lebanon', 'gd': 3},
        {'team1': 'Panama', 'team2': 'Cuba', 'gd': 1},
        {'team1': 'Albania', 'team2': 'Cyprus', 'gd': 2},
        {'team1': 'Andorra', 'team2': 'Hungary', 'gd': -5},
        {'team1': 'Argentina', 'team2': 'Paraguay', 'gd': 2},
        {'team1': 'Azerbaijan', 'team2': 'Israel', 'gd': 0},
        {'team1': 'Bulgaria', 'team2': 'Italy', 'gd': 0},
        {'team1': 'Canada', 'team2': 'Panama', 'gd': 1},
        {'team1': 'Colombia', 'team2': 'Uruguay', 'gd': 4},
        {'team1': 'Costa Rica', 'team2': 'Mexico', 'gd': -2},
        {'team1': 'Croatia', 'team2': 'Macedonia', 'gd': 1},
        {'team1': 'Cuba', 'team2': 'Honduras', 'gd': -3},
        {'team1': 'Ecuador', 'team2': 'Bolivia', 'gd': 1},
        {'team1': 'El Salvador', 'team2': 'Guyana', 'gd': 0},
        {'team1': 'Estonia', 'team2': 'Romania', 'gd': -2},
        {'team1': 'Finland', 'team2': 'France', 'gd': -1},
        {'team1': 'Georgia', 'team2': 'Belarus', 'gd': 1},
        {'team1': 'Germany', 'team2': 'Faroe Islands', 'gd': 3},
        {'team1': 'Guatemala', 'team2': 'Antigua and Barbuda', 'gd': 2},
        {'team1': 'Iceland', 'team2': 'Norway', 'gd': 2},
        {'team1': 'Jamaica', 'team2': 'USA', 'gd': 1},
        {'team1': 'Kazakhstan', 'team2': 'Ireland', 'gd': -1},
        {'team1': 'Latvia', 'team2': 'Greece', 'gd': -1},
        {'team1': 'Liechtenstein', 'team2': 'Bosnia-Herzegovina', 'gd': -7},
        {'team1': 'Lithuania', 'team2': 'Slovakia', 'gd': 0},
        {'team1': 'Luxembourg', 'team2': 'Portugal', 'gd': -1},
        {'team1': 'Malta', 'team2': 'Armenia', 'gd': -1},
        {'team1': 'Moldova', 'team2': 'England', 'gd': -5},
        {'team1': 'Montenegro', 'team2': 'Poland', 'gd': 0},
        {'team1': 'Netherlands', 'team2': 'Turkey', 'gd': 2},
        {'team1': 'New Caledonia', 'team2': 'New Zealand', 'gd': -2},
        {'team1': 'Peru', 'team2': 'Venezuela', 'gd': 1},
        {'team1': 'Russia', 'team2': 'Northern Ireland', 'gd': 2},
        {'team1': 'Slovenia', 'team2': 'Switzerland', 'gd': -2},
        {'team1': 'Solomon Islands', 'team2': 'Tahiti', 'gd': 2},
        {'team1': 'Wales', 'team2': 'Belgium', 'gd': -2},
        {'team1': 'Denmark', 'team2': 'Czech Republic', 'gd': 0},
        {'team1': 'Scotland', 'team2': 'Serbia', 'gd': 0},
        {'team1': 'Antigua and Barbuda', 'team2': 'Guatemala', 'gd': -1},
        {'team1': 'Austria', 'team2': 'Germany', 'gd': -1},
        {'team1': 'Belgium', 'team2': 'Croatia', 'gd': 0},
        {'team1': 'Bosnia-Herzegovina', 'team2': 'Latvia', 'gd': 3},
        {'team1': 'Bulgaria', 'team2': 'Armenia', 'gd': 1},
        {'team1': 'Chile', 'team2': 'Colombia', 'gd': -2},
        {'team1': 'Cyprus', 'team2': 'Iceland', 'gd': 1},
        {'team1': 'England', 'team2': 'Ukraine', 'gd': 0},
        {'team1': 'France', 'team2': 'Belarus', 'gd': 2},
        {'team1': 'Georgia', 'team2': 'Spain', 'gd': -1},
        {'team1': 'Greece', 'team2': 'Lithuania', 'gd': 2},
        {'team1': 'Guyana', 'team2': 'El Salvador', 'gd': -1},
        {'team1': 'Honduras', 'team2': 'Cuba', 'gd': 1},
        {'team1': 'Hungary', 'team2': 'Netherlands', 'gd': -3},
        {'team1': 'Israel', 'team2': 'Russia', 'gd': -4},
        {'team1': 'Italy', 'team2': 'Malta', 'gd': 2},
        {'team1': 'Japan', 'team2': 'Iraq', 'gd': 1},
        {'team1': 'Jordan', 'team2': 'Australia', 'gd': 1},
        {'team1': 'Lebanon', 'team2': 'Iran', 'gd': 1},
        {'team1': 'Mexico', 'team2': 'Costa Rica', 'gd': 1},
        {'team1': 'New Zealand', 'team2': 'Solomon Islands', 'gd': 5},
        {'team1': 'Northern Ireland', 'team2': 'Luxembourg', 'gd': 0},
        {'team1': 'Norway', 'team2': 'Slovenia', 'gd': 1},
        {'team1': 'Panama', 'team2': 'Canada', 'gd': 2},
        {'team1': 'Paraguay', 'team2': 'Venezuela', 'gd': -2},
        {'team1': 'Peru', 'team2': 'Argentina', 'gd': 0},
        {'team1': 'Poland', 'team2': 'Moldova', 'gd': 2},
        {'team1': 'Portugal', 'team2': 'Azerbaijan', 'gd': 3},
        {'team1': 'Romania', 'team2': 'Andorra', 'gd': 4},
        {'team1': 'San Marino', 'team2': 'Montenegro', 'gd': -6},
        {'team1': 'Scotland', 'team2': 'Macedonia', 'gd': 0},
        {'team1': 'Serbia', 'team2': 'Wales', 'gd': 5},
        {'team1': 'Slovakia', 'team2': 'Liechtenstein', 'gd': 2},
        {'team1': 'Sweden', 'team2': 'Kazakhstan', 'gd': 2},
        {'team1': 'Switzerland', 'team2': 'Albania', 'gd': 2},
        {'team1': 'Tahiti', 'team2': 'New Caledonia', 'gd': -4},
        {'team1': 'Turkey', 'team2': 'Estonia', 'gd': 3},
        {'team1': 'Uruguay', 'team2': 'Ecuador', 'gd': 0},
        {'team1': 'USA', 'team2': 'Jamaica', 'gd': 1},
        {'team1': 'Uzbekistan', 'team2': 'Korea Republic', 'gd': 0},
        {'team1': 'Albania', 'team2': 'Iceland', 'gd': -1},
        {'team1': 'Antigua and Barbuda', 'team2': 'USA', 'gd': -1},
        {'team1': 'Argentina', 'team2': 'Uruguay', 'gd': 3},
        {'team1': 'Armenia', 'team2': 'Italy', 'gd': -2},
        {'team1': 'Belarus', 'team2': 'Spain', 'gd': -4},
        {'team1': 'Bolivia', 'team2': 'Peru', 'gd': 0},
        {'team1': 'Bulgaria', 'team2': 'Denmark', 'gd': 0},
        {'team1': 'Canada', 'team2': 'Cuba', 'gd': 3},
        {'team1': 'Colombia', 'team2': 'Paraguay', 'gd': 2},
        {'team1': 'Czech Republic', 'team2': 'Malta', 'gd': 2},
        {'team1': 'Ecuador', 'team2': 'Chile', 'gd': 2},
        {'team1': 'El Salvador', 'team2': 'Costa Rica', 'gd': -1},
        {'team1': 'England', 'team2': 'San Marino', 'gd': 5},
        {'team1': 'Estonia', 'team2': 'Hungary', 'gd': -1},
        {'team1': 'Faroe Islands', 'team2': 'Sweden', 'gd': -1},
        {'team1': 'Finland', 'team2': 'Georgia', 'gd': 0},
        {'team1': 'Greece', 'team2': 'Bosnia-Herzegovina', 'gd': 0},
        {'team1': 'Guatemala', 'team2': 'Jamaica', 'gd': 1},
        {'team1': 'Guyana', 'team2': 'Mexico', 'gd': -5},
        {'team1': 'Ireland', 'team2': 'Germany', 'gd': -5},
        {'team1': 'Kazakhstan', 'team2': 'Austria', 'gd': 0},
        {'team1': 'Liechtenstein', 'team2': 'Lithuania', 'gd': -2},
        {'team1': 'Luxembourg', 'team2': 'Israel', 'gd': -6},
        {'team1': 'Macedonia', 'team2': 'Croatia', 'gd': -1},
        {'team1': 'Moldova', 'team2': 'Ukraine', 'gd': 0},
        {'team1': 'Netherlands', 'team2': 'Andorra', 'gd': 3},
        {'team1': 'Panama', 'team2': 'Honduras', 'gd': 0},
        {'team1': 'Russia', 'team2': 'Portugal', 'gd': 1},
        {'team1': 'Serbia', 'team2': 'Belgium', 'gd': -3},
        {'team1': 'Slovakia', 'team2': 'Latvia', 'gd': 1},
        {'team1': 'Slovenia', 'team2': 'Cyprus', 'gd': 1},
        {'team1': 'Solomon Islands', 'team2': 'New Caledonia', 'gd': -4},
        {'team1': 'Switzerland', 'team2': 'Norway', 'gd': 0},
        {'team1': 'Tahiti', 'team2': 'New Zealand', 'gd': -2},
        {'team1': 'Turkey', 'team2': 'Romania', 'gd': -1},
        {'team1': 'Wales', 'team2': 'Scotland', 'gd': 1},
        {'team1': 'Albania', 'team2': 'Slovenia', 'gd': 1},
        {'team1': 'Andorra', 'team2': 'Estonia', 'gd': -1},
        {'team1': 'Austria', 'team2': 'Kazakhstan', 'gd': 4},
        {'team1': 'Belarus', 'team2': 'Georgia', 'gd': 2},
        {'team1': 'Belgium', 'team2': 'Scotland', 'gd': 2},
        {'team1': 'Bolivia', 'team2': 'Uruguay', 'gd': 3},
        {'team1': 'Bosnia-Herzegovina', 'team2': 'Lithuania', 'gd': 3},
        {'team1': 'Chile', 'team2': 'Argentina', 'gd': -1},
        {'team1': 'Costa Rica', 'team2': 'Guyana', 'gd': 7},
        {'team1': 'Croatia', 'team2': 'Wales', 'gd': 2},
        {'team1': 'Cuba', 'team2': 'Panama', 'gd': 0},
        {'team1': 'Cyprus', 'team2': 'Norway', 'gd': -2},
        {'team1': 'Czech Republic', 'team2': 'Bulgaria', 'gd': 0},
        {'team1': 'Faroe Islands', 'team2': 'Ireland', 'gd': -3},
        {'team1': 'Germany', 'team2': 'Sweden', 'gd': 0},
        {'team1': 'Honduras', 'team2': 'Canada', 'gd': 7},
        {'team1': 'Hungary', 'team2': 'Turkey', 'gd': 2},
        {'team1': 'Iceland', 'team2': 'Switzerland', 'gd': -2},
        {'team1': 'Iran', 'team2': 'Korea Republic', 'gd': 1},
        {'team1': 'Iraq', 'team2': 'Australia', 'gd': -1},
        {'team1': 'Israel', 'team2': 'Luxembourg', 'gd': 3},
        {'team1': 'Italy', 'team2': 'Denmark', 'gd': 2},
        {'team1': 'Jamaica', 'team2': 'Antigua and Barbuda', 'gd': 3},
        {'team1': 'Latvia', 'team2': 'Liechtenstein', 'gd': 2},
        {'team1': 'Macedonia', 'team2': 'Serbia', 'gd': 1},
        {'team1': 'Mexico', 'team2': 'El Salvador', 'gd': 2},
        {'team1': 'New Caledonia', 'team2': 'Solomon Islands', 'gd': 5},
        {'team1': 'New Zealand', 'team2': 'Tahiti', 'gd': 3},
        {'team1': 'Oman', 'team2': 'Jordan', 'gd': 1},
        {'team1': 'Paraguay', 'team2': 'Peru', 'gd': 1},
        {'team1': 'Portugal', 'team2': 'Northern Ireland', 'gd': 0},
        {'team1': 'Qatar', 'team2': 'Uzbekistan', 'gd': -1},
        {'team1': 'Romania', 'team2': 'Netherlands', 'gd': -3},
        {'team1': 'Russia', 'team2': 'Azerbaijan', 'gd': 1},
        {'team1': 'San Marino', 'team2': 'Moldova', 'gd': -2},
        {'team1': 'Slovakia', 'team2': 'Greece', 'gd': -1},
        {'team1': 'Spain', 'team2': 'France', 'gd': 0},
        {'team1': 'Ukraine', 'team2': 'Montenegro', 'gd': -1},
        {'team1': 'USA', 'team2': 'Guatemala', 'gd': 2},
        {'team1': 'Venezuela', 'team2': 'Ecuador', 'gd': 0},
        {'team1': 'Poland', 'team2': 'England', 'gd': 0},
        {'team1': 'Iran', 'team2': 'Uzbekistan', 'gd': -1},
        {'team1': 'Iraq', 'team2': 'Jordan', 'gd': 1},
        {'team1': 'Montenegro', 'team2': 'San Marino', 'gd': 3},
        {'team1': 'Northern Ireland', 'team2': 'Azerbaijan', 'gd': 0},
        {'team1': 'Oman', 'team2': 'Japan', 'gd': -1},
        {'team1': 'Qatar', 'team2': 'Lebanon', 'gd': 1},
        {'team1': 'Honduras', 'team2': 'USA', 'gd': 1},
        {'team1': 'Mexico', 'team2': 'Jamaica', 'gd': 0},
        {'team1': 'Panama', 'team2': 'Costa Rica', 'gd': 0},
        {'team1': 'Andorra', 'team2': 'Turkey', 'gd': -2},
        {'team1': 'Argentina', 'team2': 'Venezuela', 'gd': 3},
        {'team1': 'Austria', 'team2': 'Faroe Islands', 'gd': 6},
        {'team1': 'Bosnia-Herzegovina', 'team2': 'Greece', 'gd': 2},
        {'team1': 'Bulgaria', 'team2': 'Malta', 'gd': 6},
        {'team1': 'Colombia', 'team2': 'Bolivia', 'gd': 5},
        {'team1': 'Croatia', 'team2': 'Serbia', 'gd': 2},
        {'team1': 'Czech Republic', 'team2': 'Denmark', 'gd': -3},
        {'team1': 'France', 'team2': 'Georgia', 'gd': 2},
        {'team1': 'Honduras', 'team2': 'Mexico', 'gd': 0},
        {'team1': 'Hungary', 'team2': 'Romania', 'gd': 0},
        {'team1': 'Israel', 'team2': 'Portugal', 'gd': 0},
        {'team1': 'Jamaica', 'team2': 'Panama', 'gd': 0},
        {'team1': 'Kazakhstan', 'team2': 'Germany', 'gd': -3},
        {'team1': 'Liechtenstein', 'team2': 'Latvia', 'gd': 0},
        {'team1': 'Luxembourg', 'team2': 'Azerbaijan', 'gd': 0},
        {'team1': 'Macedonia', 'team2': 'Belgium', 'gd': -2},
        {'team1': 'Moldova', 'team2': 'Montenegro', 'gd': -1},
        {'team1': 'Netherlands', 'team2': 'Estonia', 'gd': 3},
        {'team1': 'New Zealand', 'team2': 'New Caledonia', 'gd': 1},
        {'team1': 'Norway', 'team2': 'Albania', 'gd': -1},
        {'team1': 'Peru', 'team2': 'Chile', 'gd': 1},
        {'team1': 'Poland', 'team2': 'Ukraine', 'gd': -2},
        {'team1': 'San Marino', 'team2': 'England', 'gd': -8},
        {'team1': 'Scotland', 'team2': 'Wales', 'gd': -1},
        {'team1': 'Slovakia', 'team2': 'Lithuania', 'gd': 0},
        {'team1': 'Slovenia', 'team2': 'Iceland', 'gd': -1},
        {'team1': 'Spain', 'team2': 'Finland', 'gd': 0},
        {'team1': 'Sweden', 'team2': 'Ireland', 'gd': 0},
        {'team1': 'Tahiti', 'team2': 'Solomon Islands', 'gd': 2},
        {'team1': 'Uruguay', 'team2': 'Paraguay', 'gd': 0},
        {'team1': 'USA', 'team2': 'Costa Rica', 'gd': 1},
        {'team1': 'Burkina Faso', 'team2': 'Niger', 'gd': 4},
        {'team1': 'Cameroon', 'team2': 'Togo', 'gd': 1},
        {'team1': 'Congo', 'team2': 'Gabon', 'gd': 1},
        {'team1': 'Cyprus', 'team2': 'Switzerland', 'gd': 0},
        {'team1': 'Ivory Coast', 'team2': 'Gambia', 'gd': 3},
        {'team1': 'Namibia', 'team2': 'Malawi', 'gd': -1},
        {'team1': 'Nigeria', 'team2': 'Kenya', 'gd': 0},
        {'team1': 'Senegal', 'team2': 'Angola', 'gd': 0},
        {'team1': 'South Africa', 'team2': 'Central African Republic', 'gd': 2},
        {'team1': 'Tunisia', 'team2': 'Sierra Leone', 'gd': 1},
        {'team1': 'Congo DR', 'team2': 'Libya', 'gd': 0},
        {'team1': 'Equatorial Guinea', 'team2': 'Cape Verde', 'gd': -3},
        {'team1': 'Ethiopia', 'team2': 'Botswana', 'gd': 1},
        {'team1': 'Ghana', 'team2': 'Sudan', 'gd': 4},
        {'team1': 'Lesotho', 'team2': 'Zambia', 'gd': 0},
        {'team1': 'Liberia', 'team2': 'Uganda', 'gd': 2},
        {'team1': 'Mozambique', 'team2': 'Guinea', 'gd': 0},
        {'team1': 'Rwanda', 'team2': 'Mali', 'gd': -1},
        {'team1': 'Tanzania', 'team2': 'Morocco', 'gd': 2},
        {'team1': 'Algeria', 'team2': 'Benin', 'gd': 2},
        {'team1': 'Armenia', 'team2': 'Czech Republic', 'gd': -3},
        {'team1': 'Australia', 'team2': 'Oman', 'gd': 0},
        {'team1': 'Azerbaijan', 'team2': 'Portugal', 'gd': -2},
        {'team1': 'Belgium', 'team2': 'Macedonia', 'gd': 1},
        {'team1': 'Bolivia', 'team2': 'Argentina', 'gd': 0},
        {'team1': 'Chile', 'team2': 'Uruguay', 'gd': 2},
        {'team1': 'Costa Rica', 'team2': 'Jamaica', 'gd': 2},
        {'team1': 'Denmark', 'team2': 'Bulgaria', 'gd': 0},
        {'team1': 'Ecuador', 'team2': 'Paraguay', 'gd': 3},
        {'team1': 'Egypt', 'team2': 'Zimbabwe', 'gd': 1},
        {'team1': 'Estonia', 'team2': 'Andorra', 'gd': 2},
        {'team1': 'France', 'team2': 'Spain', 'gd': -1},
        {'team1': 'Germany', 'team2': 'Kazakhstan', 'gd': 3},
        {'team1': 'Ireland', 'team2': 'Austria', 'gd': 0},
        {'team1': 'Jordan', 'team2': 'Japan', 'gd': 1},
        {'team1': 'Korea Republic', 'team2': 'Qatar', 'gd': 1},
        {'team1': 'Malta', 'team2': 'Italy', 'gd': -2},
        {'team1': 'Mexico', 'team2': 'USA', 'gd': 0},
        {'team1': 'Montenegro', 'team2': 'England', 'gd': 0},
        {'team1': 'Netherlands', 'team2': 'Romania', 'gd': 4},
        {'team1': 'New Caledonia', 'team2': 'Tahiti', 'gd': 1},
        {'team1': 'Northern Ireland', 'team2': 'Israel', 'gd': -2},
        {'team1': 'Panama', 'team2': 'Honduras', 'gd': 2},
        {'team1': 'Poland', 'team2': 'San Marino', 'gd': 5},
        {'team1': 'Serbia', 'team2': 'Scotland', 'gd': 2},
        {'team1': 'Solomon Islands', 'team2': 'New Zealand', 'gd': -2},
        {'team1': 'Turkey', 'team2': 'Hungary', 'gd': 0},
        {'team1': 'Ukraine', 'team2': 'Moldova', 'gd': 1},
        {'team1': 'Uzbekistan', 'team2': 'Lebanon', 'gd': 1},
        {'team1': 'Venezuela', 'team2': 'Colombia', 'gd': 1},
        {'team1': 'Wales', 'team2': 'Croatia', 'gd': -1},
        {'team1': 'Jamaica', 'team2': 'Mexico', 'gd': -1},
        {'team1': 'Japan', 'team2': 'Australia', 'gd': 0},
        {'team1': 'Lebanon', 'team2': 'Korea Republic', 'gd': 0},
        {'team1': 'Oman', 'team2': 'Iraq', 'gd': 1},
        {'team1': 'Qatar', 'team2': 'Iran', 'gd': -1},
        {'team1': 'Kenya', 'team2': 'Nigeria', 'gd': -1},
        {'team1': 'Malawi', 'team2': 'Namibia', 'gd': 0},
        {'team1': 'Albania', 'team2': 'Norway', 'gd': 0},
        {'team1': 'Argentina', 'team2': 'Colombia', 'gd': 0},
        {'team1': 'Armenia', 'team2': 'Malta', 'gd': -1},
        {'team1': 'Austria', 'team2': 'Sweden', 'gd': 1},
        {'team1': 'Azerbaijan', 'team2': 'Luxembourg', 'gd': 0},
        {'team1': 'Belgium', 'team2': 'Serbia', 'gd': 1},
        {'team1': 'Bolivia', 'team2': 'Venezuela', 'gd': 0},
        {'team1': 'Costa Rica', 'team2': 'Honduras', 'gd': 1},
        {'team1': 'Croatia', 'team2': 'Scotland', 'gd': -1},
        {'team1': 'Czech Republic', 'team2': 'Italy', 'gd': 0},
        {'team1': 'Finland', 'team2': 'Belarus', 'gd': 1},
        {'team1': 'Iceland', 'team2': 'Slovenia', 'gd': -2},
        {'team1': 'Ireland', 'team2': 'Faroe Islands', 'gd': 3},
        {'team1': 'Jamaica', 'team2': 'USA', 'gd': -1},
        {'team1': 'Latvia', 'team2': 'Bosnia-Herzegovina', 'gd': -5},
        {'team1': 'Libya', 'team2': 'Congo DR', 'gd': 0},
        {'team1': 'Liechtenstein', 'team2': 'Slovakia', 'gd': 0},
        {'team1': 'Lithuania', 'team2': 'Greece', 'gd': -1},
        {'team1': 'Moldova', 'team2': 'Poland', 'gd': 0},
        {'team1': 'Montenegro', 'team2': 'Ukraine', 'gd': -4},
        {'team1': 'Panama', 'team2': 'Mexico', 'gd': 0},
        {'team1': 'Paraguay', 'team2': 'Chile', 'gd': -1},
        {'team1': 'Peru', 'team2': 'Ecuador', 'gd': 1},
        {'team1': 'Portugal', 'team2': 'Russia', 'gd': 1},
        {'team1': 'Sudan', 'team2': 'Ghana', 'gd': -2},
        {'team1': 'Angola', 'team2': 'Senegal', 'gd': 0},
        {'team1': 'Botswana', 'team2': 'Ethiopia', 'gd': 3},
        {'team1': 'Cape Verde', 'team2': 'Equatorial Guinea', 'gd': 3},
        {'team1': 'Central African Republic', 'team2': 'South Africa', 'gd': -3},
        {'team1': 'Gabon', 'team2': 'Congo', 'gd': 0},
        {'team1': 'Gambia', 'team2': 'Ivory Coast', 'gd': -3},
        {'team1': 'Morocco', 'team2': 'Tanzania', 'gd': 1},
        {'team1': 'Sierra Leone', 'team2': 'Tunisia', 'gd': 0},
        {'team1': 'Switzerland', 'team2': 'Cyprus', 'gd': 1},
        {'team1': 'Uganda', 'team2': 'Liberia', 'gd': 1},
        {'team1': 'Zambia', 'team2': 'Lesotho', 'gd': 4},
        {'team1': 'Benin', 'team2': 'Algeria', 'gd': -2},
        {'team1': 'Guinea', 'team2': 'Mozambique', 'gd': 5},
        {'team1': 'Mali', 'team2': 'Rwanda', 'gd': 0},
        {'team1': 'Niger', 'team2': 'Burkina Faso', 'gd': -1},
        {'team1': 'Togo', 'team2': 'Cameroon', 'gd': -3},
        {'team1': 'Zimbabwe', 'team2': 'Egypt', 'gd': -2},
        {'team1': 'Australia', 'team2': 'Jordan', 'gd': 4},
        {'team1': 'Belarus', 'team2': 'Finland', 'gd': 0},
        {'team1': 'Chile', 'team2': 'Bolivia', 'gd': 2},
        {'team1': 'Colombia', 'team2': 'Peru', 'gd': 2},
        {'team1': 'Denmark', 'team2': 'Armenia', 'gd': -4},
        {'team1': 'Ecuador', 'team2': 'Argentina', 'gd': 0},
        {'team1': 'Honduras', 'team2': 'Jamaica', 'gd': 2},
        {'team1': 'Iran', 'team2': 'Lebanon', 'gd': 4},
        {'team1': 'Iraq', 'team2': 'Japan', 'gd': -1},
        {'team1': 'Korea Republic', 'team2': 'Uzbekistan', 'gd': 1},
        {'team1': 'Mexico', 'team2': 'Costa Rica', 'gd': 0},
        {'team1': 'Sweden', 'team2': 'Faroe Islands', 'gd': 2},
        {'team1': 'USA', 'team2': 'Panama', 'gd': 2},
        {'team1': 'Venezuela', 'team2': 'Uruguay', 'gd': -1},
        {'team1': 'Malawi', 'team2': 'Kenya', 'gd': 0},
        {'team1': 'Namibia', 'team2': 'Nigeria', 'gd': 0},
        {'team1': 'Libya', 'team2': 'Togo', 'gd': 2},
        {'team1': 'Botswana', 'team2': 'Central African Republic', 'gd': 1},
        {'team1': 'Cape Verde', 'team2': 'Sierra Leone', 'gd': 1},
        {'team1': 'Congo', 'team2': 'Burkina Faso', 'gd': -1},
        {'team1': 'Gabon', 'team2': 'Niger', 'gd': 3},
        {'team1': 'Morocco', 'team2': 'Gambia', 'gd': 2},
        {'team1': 'Uganda', 'team2': 'Angola', 'gd': 1},
        {'team1': 'Zambia', 'team2': 'Sudan', 'gd': 0},
        {'team1': 'Congo DR', 'team2': 'Cameroon', 'gd': 0},
        {'team1': 'Equatorial Guinea', 'team2': 'Tunisia', 'gd': 0},
        {'team1': 'Ethiopia', 'team2': 'South Africa', 'gd': 1},
        {'team1': 'Guinea', 'team2': 'Zimbabwe', 'gd': 2},
        {'team1': 'Lesotho', 'team2': 'Ghana', 'gd': -2},
        {'team1': 'Liberia', 'team2': 'Senegal', 'gd': -2},
        {'team1': 'Mali', 'team2': 'Benin', 'gd': 0},
        {'team1': 'Mozambique', 'team2': 'Egypt', 'gd': -1},
        {'team1': 'Rwanda', 'team2': 'Algeria', 'gd': -1},
        {'team1': 'Tanzania', 'team2': 'Ivory Coast', 'gd': -2},
        {'team1': 'Australia', 'team2': 'Iraq', 'gd': 1},
        {'team1': 'Costa Rica', 'team2': 'Panama', 'gd': 2},
        {'team1': 'Jordan', 'team2': 'Oman', 'gd': 1},
        {'team1': 'Korea Republic', 'team2': 'Iran', 'gd': -1},
        {'team1': 'USA', 'team2': 'Honduras', 'gd': 1},
        {'team1': 'Uzbekistan', 'team2': 'Qatar', 'gd': 4},
        {'team1': 'Northern Ireland', 'team2': 'Russia', 'gd': 1},
        {'team1': 'Bosnia-Herzegovina', 'team2': 'Slovakia', 'gd': -1},
        {'team1': 'Chile', 'team2': 'Venezuela', 'gd': 3},
        {'team1': 'Colombia', 'team2': 'Ecuador', 'gd': 1},
        {'team1': 'Costa Rica', 'team2': 'USA', 'gd': 2},
        {'team1': 'Czech Republic', 'team2': 'Armenia', 'gd': -1},
        {'team1': 'England', 'team2': 'Moldova', 'gd': 4},
        {'team1': 'Estonia', 'team2': 'Netherlands', 'gd': 0},
        {'team1': 'Finland', 'team2': 'Spain', 'gd': -2},
        {'team1': 'Georgia', 'team2': 'France', 'gd': 0},
        {'team1': 'Germany', 'team2': 'Austria', 'gd': 3},
        {'team1': 'Ghana', 'team2': 'Zambia', 'gd': 1},
        {'team1': 'Ireland', 'team2': 'Sweden', 'gd': -1},
        {'team1': 'Italy', 'team2': 'Bulgaria', 'gd': 1},
        {'team1': 'Jordan', 'team2': 'Uzbekistan', 'gd': 0},
        {'team1': 'Kazakhstan', 'team2': 'Faroe Islands', 'gd': 1},
        {'team1': 'Latvia', 'team2': 'Lithuania', 'gd': 1},
        {'team1': 'Liechtenstein', 'team2': 'Greece', 'gd': -1},
        {'team1': 'Macedonia', 'team2': 'Wales', 'gd': 1},
        {'team1': 'Malta', 'team2': 'Denmark', 'gd': -1},
        {'team1': 'Mexico', 'team2': 'Honduras', 'gd': -1},
        {'team1': 'Northern Ireland', 'team2': 'Portugal', 'gd': -2},
        {'team1': 'Norway', 'team2': 'Cyprus', 'gd': 2},
        {'team1': 'Panama', 'team2': 'Jamaica', 'gd': 0},
        {'team1': 'Paraguay', 'team2': 'Bolivia', 'gd': 4},
        {'team1': 'Peru', 'team2': 'Uruguay', 'gd': -1},
        {'team1': 'Poland', 'team2': 'Montenegro', 'gd': 0},
        {'team1': 'Romania', 'team2': 'Hungary', 'gd': 3},
        {'team1': 'Russia', 'team2': 'Luxembourg', 'gd': 3},
        {'team1': 'Scotland', 'team2': 'Belgium', 'gd': -2},
        {'team1': 'Serbia', 'team2': 'Croatia', 'gd': 0},
        {'team1': 'Slovenia', 'team2': 'Albania', 'gd': 1},
        {'team1': 'Switzerland', 'team2': 'Iceland', 'gd': 0},
        {'team1': 'Turkey', 'team2': 'Andorra', 'gd': 5},
        {'team1': 'Ukraine', 'team2': 'San Marino', 'gd': 9},
        {'team1': 'Angola', 'team2': 'Liberia', 'gd': 3},
        {'team1': 'Burkina Faso', 'team2': 'Gabon', 'gd': 1},
        {'team1': 'Central African Republic', 'team2': 'Ethiopia', 'gd': -1},
        {'team1': 'Gambia', 'team2': 'Tanzania', 'gd': 2},
        {'team1': 'Israel', 'team2': 'Azerbaijan', 'gd': 0},
        {'team1': 'Ivory Coast', 'team2': 'Morocco', 'gd': 0},
        {'team1': 'Niger', 'team2': 'Congo', 'gd': 0},
        {'team1': 'Nigeria', 'team2': 'Malawi', 'gd': 2},
        {'team1': 'Senegal', 'team2': 'Uganda', 'gd': 1},
        {'team1': 'Sierra Leone', 'team2': 'Equatorial Guinea', 'gd': 1},
        {'team1': 'South Africa', 'team2': 'Botswana', 'gd': 3},
        {'team1': 'Tunisia', 'team2': 'Cape Verde', 'gd': 3},
        {'team1': 'Benin', 'team2': 'Rwanda', 'gd': 2},
        {'team1': 'Cameroon', 'team2': 'Libya', 'gd': 1},
        {'team1': 'Kenya', 'team2': 'Namibia', 'gd': 1},
        {'team1': 'Sudan', 'team2': 'Lesotho', 'gd': -2},
        {'team1': 'Togo', 'team2': 'Congo DR', 'gd': 1},
        {'team1': 'Zimbabwe', 'team2': 'Mozambique', 'gd': 0},
        {'team1': 'Algeria', 'team2': 'Mali', 'gd': 1},
        {'team1': 'Andorra', 'team2': 'Netherlands', 'gd': -2},
        {'team1': 'Armenia', 'team2': 'Denmark', 'gd': -1},
        {'team1': 'Austria', 'team2': 'Ireland', 'gd': 1},
        {'team1': 'Belarus', 'team2': 'France', 'gd': -2},
        {'team1': 'Bolivia', 'team2': 'Ecuador', 'gd': 0},
        {'team1': 'Cyprus', 'team2': 'Slovenia', 'gd': -2},
        {'team1': 'Egypt', 'team2': 'Guinea', 'gd': 2},
        {'team1': 'Faroe Islands', 'team2': 'Germany', 'gd': -3},
        {'team1': 'Georgia', 'team2': 'Finland', 'gd': -1},
        {'team1': 'Greece', 'team2': 'Latvia', 'gd': 1},
        {'team1': 'Honduras', 'team2': 'Panama', 'gd': 0},
        {'team1': 'Hungary', 'team2': 'Estonia', 'gd': 4},
        {'team1': 'Iceland', 'team2': 'Albania', 'gd': 1},
        {'team1': 'Italy', 'team2': 'Czech Republic', 'gd': 1},
        {'team1': 'Jamaica', 'team2': 'Costa Rica', 'gd': 0},
        {'team1': 'Kazakhstan', 'team2': 'Sweden', 'gd': -1},
        {'team1': 'Lithuania', 'team2': 'Liechtenstein', 'gd': 2},
        {'team1': 'Luxembourg', 'team2': 'Northern Ireland', 'gd': 1},
        {'team1': 'Macedonia', 'team2': 'Scotland', 'gd': -1},
        {'team1': 'Malta', 'team2': 'Bulgaria', 'gd': -1},
        {'team1': 'Norway', 'team2': 'Switzerland', 'gd': -2},
        {'team1': 'Paraguay', 'team2': 'Argentina', 'gd': -3},
        {'team1': 'Romania', 'team2': 'Turkey', 'gd': -2},
        {'team1': 'Russia', 'team2': 'Israel', 'gd': 2},
        {'team1': 'San Marino', 'team2': 'Poland', 'gd': -4},
        {'team1': 'Slovakia', 'team2': 'Bosnia-Herzegovina', 'gd': -1},
        {'team1': 'Ukraine', 'team2': 'England', 'gd': 0},
        {'team1': 'Uruguay', 'team2': 'Colombia', 'gd': 2},
        {'team1': 'USA', 'team2': 'Mexico', 'gd': 2},
        {'team1': 'Uzbekistan', 'team2': 'Jordan', 'gd': 0},
        {'team1': 'Venezuela', 'team2': 'Peru', 'gd': 1},
        {'team1': 'Wales', 'team2': 'Serbia', 'gd': -3},
        {'team1': 'Albania', 'team2': 'Switzerland', 'gd': -1},
        {'team1': 'Andorra', 'team2': 'Romania', 'gd': -4},
        {'team1': 'Argentina', 'team2': 'Peru', 'gd': 2},
        {'team1': 'Armenia', 'team2': 'Bulgaria', 'gd': 1},
        {'team1': 'Azerbaijan', 'team2': 'Northern Ireland', 'gd': 2},
        {'team1': 'Bosnia-Herzegovina', 'team2': 'Liechtenstein', 'gd': 3},
        {'team1': 'Colombia', 'team2': 'Chile', 'gd': 0},
        {'team1': 'Croatia', 'team2': 'Belgium', 'gd': -1},
        {'team1': 'Denmark', 'team2': 'Italy', 'gd': 0},
        {'team1': 'Ecuador', 'team2': 'Uruguay', 'gd': 1},
        {'team1': 'England', 'team2': 'Montenegro', 'gd': 3},
        {'team1': 'Estonia', 'team2': 'Turkey', 'gd': -2},
        {'team1': 'Faroe Islands', 'team2': 'Kazakhstan', 'gd': 0},
        {'team1': 'Germany', 'team2': 'Ireland', 'gd': 3},
        {'team1': 'Greece', 'team2': 'Slovakia', 'gd': 1},
        {'team1': 'Honduras', 'team2': 'Costa Rica', 'gd': 1},
        {'team1': 'Iceland', 'team2': 'Cyprus', 'gd': 2},
        {'team1': 'Lithuania', 'team2': 'Latvia', 'gd': 2},
        {'team1': 'Luxembourg', 'team2': 'Russia', 'gd': -4},
        {'team1': 'Malta', 'team2': 'Czech Republic', 'gd': -3},
        {'team1': 'Mexico', 'team2': 'Panama', 'gd': 1},
        {'team1': 'Moldova', 'team2': 'San Marino', 'gd': 3},
        {'team1': 'Netherlands', 'team2': 'Hungary', 'gd': 7},
        {'team1': 'Portugal', 'team2': 'Israel', 'gd': 0},
        {'team1': 'Slovenia', 'team2': 'Norway', 'gd': 3},
        {'team1': 'Spain', 'team2': 'Belarus', 'gd': 1},
        {'team1': 'Sweden', 'team2': 'Austria', 'gd': 1},
        {'team1': 'Ukraine', 'team2': 'Poland', 'gd': 1},
        {'team1': 'USA', 'team2': 'Jamaica', 'gd': 2},
        {'team1': 'Venezuela', 'team2': 'Paraguay', 'gd': 0},
        {'team1': 'Wales', 'team2': 'Macedonia', 'gd': 1},
        {'team1': 'Burkina Faso', 'team2': 'Algeria', 'gd': 1},
        {'team1': 'Ivory Coast', 'team2': 'Senegal', 'gd': 2},
        {'team1': 'Ethiopia', 'team2': 'Nigeria', 'gd': -1},
        {'team1': 'Tunisia', 'team2': 'Cameroon', 'gd': 0},
        {'team1': 'Azerbaijan', 'team2': 'Russia', 'gd': 0},
        {'team1': 'Belgium', 'team2': 'Wales', 'gd': 0},
        {'team1': 'Bulgaria', 'team2': 'Czech Republic', 'gd': -1},
        {'team1': 'Chile', 'team2': 'Ecuador', 'gd': 1},
        {'team1': 'Costa Rica', 'team2': 'Mexico', 'gd': 1},
        {'team1': 'Cyprus', 'team2': 'Albania', 'gd': 0},
        {'team1': 'Denmark', 'team2': 'Malta', 'gd': 6},
        {'team1': 'England', 'team2': 'Poland', 'gd': 2},
        {'team1': 'Faroe Islands', 'team2': 'Austria', 'gd': -3},
        {'team1': 'France', 'team2': 'Finland', 'gd': 3},
        {'team1': 'Ghana', 'team2': 'Egypt', 'gd': 5},
        {'team1': 'Greece', 'team2': 'Liechtenstein', 'gd': 2},
        {'team1': 'Hungary', 'team2': 'Andorra', 'gd': 2},
        {'team1': 'Ireland', 'team2': 'Kazakhstan', 'gd': 2},
        {'team1': 'Israel', 'team2': 'Northern Ireland', 'gd': 0},
        {'team1': 'Italy', 'team2': 'Armenia', 'gd': 0},
        {'team1': 'Jamaica', 'team2': 'Honduras', 'gd': 0},
        {'team1': 'Latvia', 'team2': 'Slovakia', 'gd': 0},
        {'team1': 'Lithuania', 'team2': 'Bosnia-Herzegovina', 'gd': -1},
        {'team1': 'Montenegro', 'team2': 'Moldova', 'gd': -3},
        {'team1': 'Norway', 'team2': 'Iceland', 'gd': 0},
        {'team1': 'Panama', 'team2': 'USA', 'gd': -1},
        {'team1': 'Paraguay', 'team2': 'Colombia', 'gd': -1},
        {'team1': 'Peru', 'team2': 'Bolivia', 'gd': 0},
        {'team1': 'Portugal', 'team2': 'Luxembourg', 'gd': 3},
        {'team1': 'Romania', 'team2': 'Estonia', 'gd': 2},
        {'team1': 'San Marino', 'team2': 'Ukraine', 'gd': -8},
        {'team1': 'Scotland', 'team2': 'Croatia', 'gd': 2},
        {'team1': 'Serbia', 'team2': 'Macedonia', 'gd': 4},
        {'team1': 'Spain', 'team2': 'Georgia', 'gd': 2},
        {'team1': 'Sweden', 'team2': 'Germany', 'gd': -2},
        {'team1': 'Switzerland', 'team2': 'Slovenia', 'gd': 1},
        {'team1': 'Turkey', 'team2': 'Netherlands', 'gd': -2},
        {'team1': 'Uruguay', 'team2': 'Argentina', 'gd': 1},
        {'team1': 'Jordan', 'team2': 'Uruguay', 'gd': -5},
        {'team1': 'Greece', 'team2': 'Romania', 'gd': 2},
        {'team1': 'Iceland', 'team2': 'Croatia', 'gd': 0},
        {'team1': 'Portugal', 'team2': 'Sweden', 'gd': 1},
        {'team1': 'Ukraine', 'team2': 'France', 'gd': 2},
        {'team1': 'Nigeria', 'team2': 'Ethiopia', 'gd': 2},
        {'team1': 'Senegal', 'team2': 'Ivory Coast', 'gd': 0},
        {'team1': 'Cameroon', 'team2': 'Tunisia', 'gd': 3},
        {'team1': 'Algeria', 'team2': 'Burkina Faso', 'gd': 1},
        {'team1': 'Croatia', 'team2': 'Iceland', 'gd': 2},
        {'team1': 'Egypt', 'team2': 'Ghana', 'gd': 1},
        {'team1': 'France', 'team2': 'Ukraine', 'gd': 3},
        {'team1': 'Romania', 'team2': 'Greece', 'gd': 0},
        {'team1': 'Sweden', 'team2': 'Portugal', 'gd': -1},
        {'team1': 'New Zealand', 'team2': 'Mexico', 'gd': -2},
        {'team1': 'Uruguay', 'team2': 'Jordan', 'gd': 0},
        {'team1': 'Niger', 'team2': 'Togo', 'gd': 2},
        {'team1': 'Qatar', 'team2': 'United Arab Emirates', 'gd': -2},
        {'team1': 'Zambia', 'team2': 'Angola', 'gd': -2},
        {'team1': 'Kenya', 'team2': 'Burundi', 'gd': 0},
        {'team1': 'Kuwait', 'team2': 'Yemen', 'gd': 2},
        {'team1': 'Saudi Arabia', 'team2': 'Iraq', 'gd': -2},
        {'team1': 'Tunisia', 'team2': 'Ethiopia', 'gd': 0},
        {'team1': 'Bahrain', 'team2': 'United Arab Emirates', 'gd': -1},
        {'team1': 'Qatar', 'team2': 'Oman', 'gd': 1},
        {'team1': 'South Africa', 'team2': 'Norway', 'gd': -1},
        {'team1': 'Zambia', 'team2': 'Morocco', 'gd': 0},
        {'team1': 'Cape Verde', 'team2': 'Nigeria', 'gd': 0},
        {'team1': 'Iraq', 'team2': 'Kuwait', 'gd': 1},
        {'team1': 'Yemen', 'team2': 'Saudi Arabia', 'gd': -2},
        {'team1': 'Gabon', 'team2': 'Tunisia', 'gd': 0},
        {'team1': 'Bahrain', 'team2': 'Qatar', 'gd': 1},
        {'team1': 'Iraq', 'team2': 'Yemen', 'gd': 2},
        {'team1': 'Namibia', 'team2': 'Morocco', 'gd': -1},
        {'team1': 'South Africa', 'team2': 'Algeria', 'gd': 0},
        {'team1': 'Zambia', 'team2': 'Norway', 'gd': 0},
        {'team1': 'Panama', 'team2': 'Guatemala', 'gd': 2},
        {'team1': 'Togo', 'team2': 'Niger', 'gd': 1},
        {'team1': 'Ivory Coast', 'team2': 'Egypt', 'gd': 2},
        {'team1': 'Chile', 'team2': 'Haiti', 'gd': 3},
        {'team1': 'Costa Rica', 'team2': 'Nicaragua', 'gd': 2},
        {'team1': 'Mali', 'team2': 'Niger', 'gd': 1},
        {'team1': 'Zambia', 'team2': 'Nigeria', 'gd': 0},
        {'team1': 'El Salvador', 'team2': 'Belize', 'gd': 1},
        {'team1': 'USA', 'team2': 'Canada', 'gd': 0},
        {'team1': 'Jordan', 'team2': 'Indonesia', 'gd': 5},
        {'team1': 'Romania', 'team2': 'Poland', 'gd': -3},
        {'team1': 'South Africa', 'team2': 'Mali', 'gd': 0},
        {'team1': 'Albania', 'team2': 'Georgia', 'gd': -1},
        {'team1': 'Burkina Faso', 'team2': 'Ghana', 'gd': 0},
        {'team1': 'Burma', 'team2': 'Philippines', 'gd': -1},
        {'team1': 'Chile', 'team2': 'Egypt', 'gd': 1},
        {'team1': 'France', 'team2': 'Germany', 'gd': -1},
        {'team1': 'Hungary', 'team2': 'Belarus', 'gd': 0},
        {'team1': 'Iceland', 'team2': 'Russia', 'gd': -2},
        {'team1': 'Iran', 'team2': 'Lebanon', 'gd': 5},
        {'team1': 'Japan', 'team2': 'Latvia', 'gd': 3},
        {'team1': 'Mali', 'team2': 'Ghana', 'gd': 2},
        {'team1': 'Burma', 'team2': 'Guam', 'gd': 5},
        {'team1': 'Sweden', 'team2': 'Ireland', 'gd': 0},
        {'team1': 'Tahiti', 'team2': 'Solomon Islands', 'gd': 2},
        {'team1': 'Turkmenistan', 'team2': 'Cambodia', 'gd': 7},
        {'team1': 'United Arab Emirates', 'team2': 'Uzbekistan', 'gd': 1},
        {'team1': 'Uruguay', 'team2': 'Paraguay', 'gd': 0},
        {'team1': 'USA', 'team2': 'Costa Rica', 'gd': 1},
        {'team1': 'Belize', 'team2': 'Trinidad and Tobago', 'gd': 0},
        {'team1': 'Burkina Faso', 'team2': 'Niger', 'gd': 4},
        {'team1': 'Cameroon', 'team2': 'Togo', 'gd': 1},
        {'team1': 'Congo', 'team2': 'Gabon', 'gd': 1},
        {'team1': 'Cyprus', 'team2': 'Switzerland', 'gd': 0},
        {'team1': 'Indonesia', 'team2': 'Saudi Arabia', 'gd': -1},
        {'team1': 'Ivory Coast', 'team2': 'Gambia', 'gd': 3},
        {'team1': 'Namibia', 'team2': 'Malawi', 'gd': -1},
        {'team1': 'Nigeria', 'team2': 'Kenya', 'gd': 0},
        {'team1': 'Senegal', 'team2': 'Angola', 'gd': 0},
        {'team1': 'South Africa', 'team2': 'Central African Republic', 'gd': 2},
        {'team1': 'Tunisia', 'team2': 'Sierra Leone', 'gd': 1},
        {'team1': 'Cambodia', 'team2': 'Philippines', 'gd': -8},
        {'team1': 'Congo DR', 'team2': 'Libya', 'gd': 0},
        {'team1': 'Dominican Republic', 'team2': 'Haiti', 'gd': 2},
        {'team1': 'Equatorial Guinea', 'team2': 'Cape Verde', 'gd': -3},
        {'team1': 'Ethiopia', 'team2': 'Botswana', 'gd': 1},
        {'team1': 'Ghana', 'team2': 'Sudan', 'gd': 4},
        {'team1': 'Lesotho', 'team2': 'Zambia', 'gd': 0},
        {'team1': 'Liberia', 'team2': 'Uganda', 'gd': 2},
        {'team1': 'Mozambique', 'team2': 'Guinea', 'gd': 0},
        {'team1': 'Rwanda', 'team2': 'Mali', 'gd': -1},
        {'team1': 'Tanzania', 'team2': 'Morocco', 'gd': 2},
        {'team1': 'Canada', 'team2': 'Belarus', 'gd': -2},
        {'team1': 'Russia', 'team2': 'Brazil', 'gd': 0},
        {'team1': 'Albania', 'team2': 'Lithuania', 'gd': 3},
        {'team1': 'Armenia', 'team2': 'Czech Republic', 'gd': -3},
        {'team1': 'Australia', 'team2': 'Oman', 'gd': 0},
        {'team1': 'Azerbaijan', 'team2': 'Portugal', 'gd': -2},
        {'team1': 'Belgium', 'team2': 'Macedonia', 'gd': 1},
        {'team1': 'Chile', 'team2': 'Uruguay', 'gd': 2},
        {'team1': 'Costa Rica', 'team2': 'Jamaica', 'gd': 2},
        {'team1': 'Denmark', 'team2': 'Bulgaria', 'gd': 0},
        {'team1': 'Ecuador', 'team2': 'Paraguay', 'gd': 3},
        {'team1': 'Egypt', 'team2': 'Zimbabwe', 'gd': 1},
        {'team1': 'Estonia', 'team2': 'Andorra', 'gd': 2},
        {'team1': 'France', 'team2': 'Spain', 'gd': -1},
        {'team1': 'Germany', 'team2': 'Kazakhstan', 'gd': 3},
        {'team1': 'Iraq', 'team2': 'Syria', 'gd': 1},
        {'team1': 'Ireland', 'team2': 'Austria', 'gd': 0},
        {'team1': 'Korea Republic', 'team2': 'Qatar', 'gd': 1},
        {'team1': 'Luxembourg', 'team2': 'Finland', 'gd': -3},
        {'team1': 'Montenegro', 'team2': 'England', 'gd': 0},
        {'team1': 'Netherlands', 'team2': 'Romania', 'gd': 4},
        {'team1': 'Northern Ireland', 'team2': 'Israel', 'gd': -2},
        {'team1': 'Solomon Islands', 'team2': 'New Zealand', 'gd': -2},
        {'team1': 'Uzbekistan', 'team2': 'Lebanon', 'gd': 1},
        {'team1': 'Mexico', 'team2': 'Peru', 'gd': 0},
        {'team1': 'Zambia', 'team2': 'Zimbabwe', 'gd': 2},
        {'team1': 'Oman', 'team2': 'Iran', 'gd': 2},
        {'team1': 'Qatar', 'team2': 'Latvia', 'gd': 2},
        {'team1': 'Qatar', 'team2': 'Azerbaijan', 'gd': 0},
        {'team1': 'Italy', 'team2': 'San Marino', 'gd': 4},
        {'team1': 'Mexico', 'team2': 'Nigeria', 'gd': 0},
        {'team1': 'Libya', 'team2': 'Uganda', 'gd': 3},
        {'team1': 'Qatar', 'team2': 'Iran', 'gd': -1},
        {'team1': 'Belgium', 'team2': 'Serbia', 'gd': 1},
        {'team1': 'Finland', 'team2': 'Belarus', 'gd': 1},
        {'team1': 'Indonesia', 'team2': 'Netherlands', 'gd': -3},
        {'team1': 'Montenegro', 'team2': 'Ukraine', 'gd': -4},
        {'team1': 'Panama', 'team2': 'Mexico', 'gd': 0},
        {'team1': 'Paraguay', 'team2': 'Chile', 'gd': -1},
        {'team1': 'Central African Republic', 'team2': 'South Africa', 'gd': -3},
        {'team1': 'Sierra Leone', 'team2': 'Tunisia', 'gd': 0},
        {'team1': 'Uganda', 'team2': 'Liberia', 'gd': 1},
        {'team1': 'Mali', 'team2': 'Rwanda', 'gd': 0},
        {'team1': 'Chile', 'team2': 'Bolivia', 'gd': 2},
        {'team1': 'China', 'team2': 'Netherlands', 'gd': -2},
        {'team1': 'Iran', 'team2': 'Lebanon', 'gd': 4},
        {'team1': 'Iraq', 'team2': 'Japan', 'gd': -1},
        {'team1': 'Italy', 'team2': 'Haiti', 'gd': 0},
        {'team1': 'Korea Republic', 'team2': 'Uzbekistan', 'gd': 1},
        {'team1': 'Mexico', 'team2': 'Costa Rica', 'gd': 0},
        {'team1': 'Norway', 'team2': 'Macedonia', 'gd': 2},
        {'team1': 'Qatar', 'team2': 'Korea DPR', 'gd': 0},
        {'team1': 'Spain', 'team2': 'Ireland', 'gd': 2},
        {'team1': 'Sweden', 'team2': 'Faroe Islands', 'gd': 2},
        {'team1': 'Congo', 'team2': 'Burkina Faso', 'gd': -1},
        {'team1': 'Liberia', 'team2': 'Senegal', 'gd': -2},
        {'team1': 'Mexico', 'team2': 'Italy', 'gd': -1},
        {'team1': 'Rwanda', 'team2': 'Algeria', 'gd': -1},
        {'team1': 'Brazil', 'team2': 'Mexico', 'gd': 2},
        {'team1': 'Italy', 'team2': 'Brazil', 'gd': -2},
        {'team1': 'Swaziland', 'team2': 'Angola', 'gd': -1},
        {'team1': 'Kenya', 'team2': 'Swaziland', 'gd': 2},
        {'team1': 'Lesotho', 'team2': 'Botswana', 'gd': 0},
        {'team1': 'South Africa', 'team2': 'Namibia', 'gd': 1},
        {'team1': 'USA', 'team2': 'Costa Rica', 'gd': 1},
        {'team1': 'Lesotho', 'team2': 'South Africa', 'gd': -1},
        {'team1': 'Mauritania', 'team2': 'Senegal', 'gd': 2},
        {'team1': 'Mexico', 'team2': 'Trinidad and Tobago', 'gd': 1},
        {'team1': 'Panama', 'team2': 'Cuba', 'gd': 5},
        {'team1': 'Zimbabwe', 'team2': 'Zambia', 'gd': -2},
        {'team1': 'Honduras', 'team2': 'Costa Rica', 'gd': 1},
        {'team1': 'USA', 'team2': 'El Salvador', 'gd': 4},
        {'team1': 'USA', 'team2': 'Honduras', 'gd': 2},
        {'team1': 'Japan', 'team2': 'Australia', 'gd': 1},
        {'team1': 'Niger', 'team2': 'Burkina Faso', 'gd': 1},
        {'team1': 'Uganda', 'team2': 'Tanzania', 'gd': 2},
        {'team1': 'Australia', 'team2': 'China', 'gd': -1},
        {'team1': 'Cameroon', 'team2': 'Gabon', 'gd': 1},
        {'team1': 'Congo', 'team2': 'Congo DR', 'gd': 1},
        {'team1': 'Mauritius', 'team2': 'Zimbabwe', 'gd': -3},
        {'team1': 'Mozambique', 'team2': 'Namibia', 'gd': 3},
        {'team1': 'Sudan', 'team2': 'Burundi', 'gd': 0},
        {'team1': 'USA', 'team2': 'Panama', 'gd': 1},
        {'team1': 'Namibia', 'team2': 'Mozambique', 'gd': 3},
        {'team1': 'Gabon', 'team2': 'Cameroon', 'gd': 1},
        {'team1': 'Jordan', 'team2': 'Libya', 'gd': 1},
        {'team1': 'Algeria', 'team2': 'Guinea', 'gd': 0},
        {'team1': 'Azerbaijan', 'team2': 'Malta', 'gd': 3},
        {'team1': 'Belarus', 'team2': 'Montenegro', 'gd': 0},
        {'team1': 'Chile', 'team2': 'Iraq', 'gd': 6},
        {'team1': 'Finland', 'team2': 'Slovenia', 'gd': 2},
        {'team1': 'Gabon', 'team2': 'Cape Verde', 'gd': 0},
        {'team1': 'Germany', 'team2': 'Paraguay', 'gd': 0},
        {'team1': 'Indonesia', 'team2': 'Philippines', 'gd': 2},
        {'team1': 'Italy', 'team2': 'Argentina', 'gd': -1},
        {'team1': 'Kazakhstan', 'team2': 'Georgia', 'gd': 1},
        {'team1': 'Korea Republic', 'team2': 'Peru', 'gd': 0},
        {'team1': 'Libya', 'team2': 'Central African Republic', 'gd': 0},
        {'team1': 'Liechtenstein', 'team2': 'Croatia', 'gd': -1},
        {'team1': 'Macedonia', 'team2': 'Bulgaria', 'gd': 2},
        {'team1': 'Mexico', 'team2': 'Ivory Coast', 'gd': 3},
        {'team1': 'Morocco', 'team2': 'Burkina Faso', 'gd': -1},
        {'team1': 'Northern Ireland', 'team2': 'Russia', 'gd': 1},
        {'team1': 'Poland', 'team2': 'Denmark', 'gd': 1},
        {'team1': 'Singapore', 'team2': 'Oman', 'gd': -2},
        {'team1': 'Sweden', 'team2': 'Norway', 'gd': 2},
        {'team1': 'Switzerland', 'team2': 'Brazil', 'gd': 1},
        {'team1': 'Tunisia', 'team2': 'Congo', 'gd': 3},
        {'team1': 'Venezuela', 'team2': 'Bolivia', 'gd': 0},
        {'team1': 'Zambia', 'team2': 'Senegal', 'gd': 0},
        {'team1': 'South Africa', 'team2': 'Burkina Faso', 'gd': 2},
        {'team1': 'Zimbabwe', 'team2': 'Zambia', 'gd': 0},
        {'team1': 'Afghanistan', 'team2': 'Pakistan', 'gd': 3},
        {'team1': 'Zambia', 'team2': 'Zimbabwe', 'gd': -1},
        {'team1': 'Mozambique', 'team2': 'Angola', 'gd': 0},
        {'team1': 'Libya', 'team2': 'Mali', 'gd': 1},
        {'team1': 'Botswana', 'team2': 'Uganda', 'gd': -2},
        {'team1': 'Congo DR', 'team2': 'Cameroon', 'gd': 0},
        {'team1': 'Nepal', 'team2': 'Bangladesh', 'gd': 2},
        {'team1': 'India', 'team2': 'Pakistan', 'gd': 1},
        {'team1': 'Afghanistan', 'team2': 'Bhutan', 'gd': 3},
        {'team1': 'Pakistan', 'team2': 'Nepal', 'gd': 0},
        {'team1': 'Equatorial Guinea', 'team2': 'Libya', 'gd': 0},
        {'team1': 'Qatar', 'team2': 'Mauritius', 'gd': 3},
        {'team1': 'Afghanistan', 'team2': 'Maldives', 'gd': 0},
        {'team1': 'Burma', 'team2': 'Hong Kong', 'gd': 0},
        {'team1': 'Latvia', 'team2': 'Lithuania', 'gd': 1},
        {'team1': 'Lebanon', 'team2': 'Syria', 'gd': 2},
        {'team1': 'Romania', 'team2': 'Hungary', 'gd': 3},
        {'team1': 'Russia', 'team2': 'Luxembourg', 'gd': 3},
        {'team1': 'Sri Lanka', 'team2': 'Bhutan', 'gd': 3},
        {'team1': 'Israel', 'team2': 'Azerbaijan', 'gd': 0},
        {'team1': 'Tunisia', 'team2': 'Cape Verde', 'gd': 3},
        {'team1': 'Canada', 'team2': 'Mauritania', 'gd': 0},
        {'team1': 'Togo', 'team2': 'Congo DR', 'gd': 1},
        {'team1': 'Qatar', 'team2': 'Lebanon', 'gd': 0},
        {'team1': 'United Arab Emirates', 'team2': 'New Zealand', 'gd': 2},
        {'team1': 'Andorra', 'team2': 'Netherlands', 'gd': -2},
        {'team1': 'Armenia', 'team2': 'Denmark', 'gd': -1},
        {'team1': 'Canada', 'team2': 'Mauritania', 'gd': -1},
        {'team1': 'Georgia', 'team2': 'Finland', 'gd': -1},
        {'team1': 'Hong Kong', 'team2': 'Singapore', 'gd': 1},
        {'team1': 'Hungary', 'team2': 'Estonia', 'gd': 4},
        {'team1': 'Iceland', 'team2': 'Albania', 'gd': 1},
        {'team1': 'Italy', 'team2': 'Czech Republic', 'gd': 1},
        {'team1': 'Japan', 'team2': 'Ghana', 'gd': 2},
        {'team1': 'Kazakhstan', 'team2': 'Sweden', 'gd': -1},
        {'team1': 'Korea Republic', 'team2': 'Croatia', 'gd': -1},
        {'team1': 'Lithuania', 'team2': 'Liechtenstein', 'gd': 2},
        {'team1': 'Luxembourg', 'team2': 'Northern Ireland', 'gd': 1},
        {'team1': 'Macedonia', 'team2': 'Scotland', 'gd': -1},
        {'team1': 'Malta', 'team2': 'Bulgaria', 'gd': -1},
        {'team1': 'Nigeria', 'team2': 'Burkina Faso', 'gd': 3},
        {'team1': 'Norway', 'team2': 'Switzerland', 'gd': -2},
        {'team1': 'Paraguay', 'team2': 'Argentina', 'gd': -3},
        {'team1': 'Romania', 'team2': 'Turkey', 'gd': -2},
        {'team1': 'Russia', 'team2': 'Israel', 'gd': 2},
        {'team1': 'San Marino', 'team2': 'Poland', 'gd': -4},
        {'team1': 'Slovakia', 'team2': 'Bosnia-Herzegovina', 'gd': -1},
        {'team1': 'South Africa', 'team2': 'Zimbabwe', 'gd': -1},
        {'team1': 'Spain', 'team2': 'Chile', 'gd': 0},
        {'team1': 'Ukraine', 'team2': 'England', 'gd': 0},
        {'team1': 'Uruguay', 'team2': 'Colombia', 'gd': 2},
        {'team1': 'USA', 'team2': 'Mexico', 'gd': 2},
        {'team1': 'Uzbekistan', 'team2': 'Jordan', 'gd': 0},
        {'team1': 'Venezuela', 'team2': 'Peru', 'gd': 1},
        {'team1': 'Wales', 'team2': 'Serbia', 'gd': -3},
        {'team1': 'Botswana', 'team2': 'Burkina Faso', 'gd': 1},
        {'team1': 'Iraq', 'team2': 'Yemen', 'gd': 1},
        {'team1': 'Lebanon', 'team2': 'Iraq', 'gd': 0},
        {'team1': 'Jordan', 'team2': 'Kuwait', 'gd': 0},
        {'team1': 'Qatar', 'team2': 'Vietnam', 'gd': -1},
        {'team1': 'Singapore', 'team2': 'Laos', 'gd': 1},
        {'team1': 'Thailand', 'team2': 'Bahrain', 'gd': 1},
        {'team1': 'Albania', 'team2': 'Switzerland', 'gd': -1},
        {'team1': 'Andorra', 'team2': 'Romania', 'gd': -4},
        {'team1': 'Argentina', 'team2': 'Peru', 'gd': 2},
        {'team1': 'Armenia', 'team2': 'Bulgaria', 'gd': 1},
        {'team1': 'Azerbaijan', 'team2': 'Northern Ireland', 'gd': 2},
        {'team1': 'Bosnia-Herzegovina', 'team2': 'Liechtenstein', 'gd': 3},
        {'team1': 'Colombia', 'team2': 'Chile', 'gd': 0},
        {'team1': 'Croatia', 'team2': 'Belgium', 'gd': -1},
        {'team1': 'Ecuador', 'team2': 'Uruguay', 'gd': 1},
        {'team1': 'England', 'team2': 'Montenegro', 'gd': 3},
        {'team1': 'Estonia', 'team2': 'Turkey', 'gd': -2},
        {'team1': 'France', 'team2': 'Australia', 'gd': 6},
        {'team1': 'Germany', 'team2': 'Ireland', 'gd': 3},
        {'team1': 'Honduras', 'team2': 'Costa Rica', 'gd': 1},
        {'team1': 'Iceland', 'team2': 'Cyprus', 'gd': 2},
        {'team1': 'Lithuania', 'team2': 'Latvia', 'gd': 2},
        {'team1': 'Luxembourg', 'team2': 'Russia', 'gd': -4},
        {'team1': 'Mexico', 'team2': 'Panama', 'gd': 1},
        {'team1': 'Moldova', 'team2': 'San Marino', 'gd': 3},
        {'team1': 'Philippines', 'team2': 'Taiwan', 'gd': -1},
        {'team1': 'Serbia', 'team2': 'Japan', 'gd': 2},
        {'team1': 'Slovenia', 'team2': 'Norway', 'gd': 3},
        {'team1': 'Spain', 'team2': 'Belarus', 'gd': 1},
        {'team1': 'Sweden', 'team2': 'Austria', 'gd': 1},
        {'team1': 'Ukraine', 'team2': 'Poland', 'gd': 1},
        {'team1': 'USA', 'team2': 'Jamaica', 'gd': 2},
        {'team1': 'Venezuela', 'team2': 'Paraguay', 'gd': 0},
        {'team1': 'Wales', 'team2': 'Macedonia', 'gd': 1},
        {'team1': 'Burkina Faso', 'team2': 'Algeria', 'gd': 1},
        {'team1': 'Korea Republic', 'team2': 'Brazil', 'gd': -2},
        {'team1': 'Ethiopia', 'team2': 'Nigeria', 'gd': -1},
        {'team1': 'Qatar', 'team2': 'Yemen', 'gd': 6},
        {'team1': 'Australia', 'team2': 'Canada', 'gd': 3},
        {'team1': 'Azerbaijan', 'team2': 'Russia', 'gd': 0},
        {'team1': 'Brazil', 'team2': 'Zambia', 'gd': 2},
        {'team1': 'Bulgaria', 'team2': 'Czech Republic', 'gd': -1},
        {'team1': 'Chile', 'team2': 'Ecuador', 'gd': 1},
        {'team1': 'Costa Rica', 'team2': 'Mexico', 'gd': 1},
        {'team1': 'Faroe Islands', 'team2': 'Austria', 'gd': -3},
        {'team1': 'Ghana', 'team2': 'Egypt', 'gd': 5},
        {'team1': 'Israel', 'team2': 'Northern Ireland', 'gd': 0},
        {'team1': 'Jordan', 'team2': 'Oman', 'gd': 0},
        {'team1': 'Kyrgyzstan', 'team2': 'Tajikistan', 'gd': -3},
        {'team1': 'Latvia', 'team2': 'Slovakia', 'gd': 0},
        {'team1': 'Lithuania', 'team2': 'Bosnia-Herzegovina', 'gd': -1},
        {'team1': 'Montenegro', 'team2': 'Moldova', 'gd': -3},
        {'team1': 'Panama', 'team2': 'USA', 'gd': -1},
        {'team1': 'Paraguay', 'team2': 'Colombia', 'gd': -1},
        {'team1': 'Portugal', 'team2': 'Luxembourg', 'gd': 3},
        {'team1': 'San Marino', 'team2': 'Ukraine', 'gd': -8},
        {'team1': 'Serbia', 'team2': 'Macedonia', 'gd': 4},
        {'team1': 'Singapore', 'team2': 'Syria', 'gd': 1},
        {'team1': 'Spain', 'team2': 'Georgia', 'gd': 2},
        {'team1': 'Sweden', 'team2': 'Germany', 'gd': -2},
        {'team1': 'Switzerland', 'team2': 'Slovenia', 'gd': 1},
        {'team1': 'Trinidad and Tobago', 'team2': 'New Zealand', 'gd': 0},
        {'team1': 'Turkey', 'team2': 'Netherlands', 'gd': -2},
        {'team1': 'Uruguay', 'team2': 'Argentina', 'gd': 1},
        {'team1': 'Uzbekistan', 'team2': 'Vietnam', 'gd': 2},
        {'team1': 'Jordan', 'team2': 'Nigeria', 'gd': 1},
        {'team1': 'Indonesia', 'team2': 'Kyrgyzstan', 'gd': 4},
        {'team1': 'Jordan', 'team2': 'Zambia', 'gd': 1},
        {'team1': 'Kuwait', 'team2': 'Malaysia', 'gd': 3},
        {'team1': 'Bahrain', 'team2': 'Lebanon', 'gd': 1},
        {'team1': 'United Arab Emirates', 'team2': 'Philippines', 'gd': 4},
        {'team1': 'CuraÃ§ao', 'team2': 'Aruba', 'gd': 2},
        {'team1': 'Egypt', 'team2': 'Zambia', 'gd': 2},
        {'team1': 'Argentina', 'team2': 'Ecuador', 'gd': 0},
        {'team1': 'Bahrain', 'team2': 'Malaysia', 'gd': 1},
        {'team1': 'Belarus', 'team2': 'Albania', 'gd': 0},
        {'team1': 'China', 'team2': 'Indonesia', 'gd': 1},
        {'team1': 'Denmark', 'team2': 'Norway', 'gd': 1},
        {'team1': 'Estonia', 'team2': 'Azerbaijan', 'gd': 1},
        {'team1': 'Iceland', 'team2': 'Croatia', 'gd': 0},
        {'team1': 'India', 'team2': 'Philippines', 'gd': 0},
        {'team1': 'Italy', 'team2': 'Germany', 'gd': 0},
        {'team1': 'Jamaica', 'team2': 'Trinidad and Tobago', 'gd': -1},
        {'team1': 'Kuwait', 'team2': 'Lebanon', 'gd': 0},
        {'team1': 'Poland', 'team2': 'Slovakia', 'gd': -2},
        {'team1': 'Russia', 'team2': 'Serbia', 'gd': 0},
        {'team1': 'Swaziland', 'team2': 'South Africa', 'gd': -3},
        {'team1': 'Syria', 'team2': 'Singapore', 'gd': 4},
        {'team1': 'Thailand', 'team2': 'Iran', 'gd': -3},
        {'team1': 'Turkey', 'team2': 'Northern Ireland', 'gd': 1},
        {'team1': 'Ukraine', 'team2': 'France', 'gd': 2},
        {'team1': 'Vietnam', 'team2': 'Uzbekistan', 'gd': -3},
        {'team1': 'Yemen', 'team2': 'Qatar', 'gd': -3},
        {'team1': 'Equatorial Guinea', 'team2': 'Spain', 'gd': -1},
        {'team1': 'Netherlands', 'team2': 'Japan', 'gd': 0},
        {'team1': 'Nigeria', 'team2': 'Ethiopia', 'gd': 2},
        {'team1': 'Senegal', 'team2': 'Ivory Coast', 'gd': 0},
        {'team1': 'Uganda', 'team2': 'Rwanda', 'gd': 0},
        {'team1': 'Austria', 'team2': 'USA', 'gd': 1},
        {'team1': 'Bahrain', 'team2': 'Yemen', 'gd': 2},
        {'team1': 'Belgium', 'team2': 'Japan', 'gd': -1},
        {'team1': 'Cambodia', 'team2': 'Guam', 'gd': -2},
        {'team1': 'Croatia', 'team2': 'Iceland', 'gd': 2},
        {'team1': 'France', 'team2': 'Ukraine', 'gd': 3},
        {'team1': 'Honduras', 'team2': 'Ecuador', 'gd': 0},
        {'team1': 'India', 'team2': 'Nepal', 'gd': 2},
        {'team1': 'Indonesia', 'team2': 'Iraq', 'gd': -2},
        {'team1': 'Kuwait', 'team2': 'Thailand', 'gd': 2},
        {'team1': 'Kyrgyzstan', 'team2': 'Azerbaijan', 'gd': 0},
        {'team1': 'Lebanon', 'team2': 'Iran', 'gd': -3},
        {'team1': 'Liechtenstein', 'team2': 'Estonia', 'gd': -3},
        {'team1': 'Malaysia', 'team2': 'Qatar', 'gd': -1},
        {'team1': 'Malta', 'team2': 'Faroe Islands', 'gd': 1},
        {'team1': 'Namibia', 'team2': 'Mozambique', 'gd': 0},
        {'team1': 'Netherlands', 'team2': 'Colombia', 'gd': 0},
        {'team1': 'Norway', 'team2': 'Scotland', 'gd': -1},
        {'team1': 'Poland', 'team2': 'Ireland', 'gd': 0},
        {'team1': 'Romania', 'team2': 'Greece', 'gd': 0},
        {'team1': 'Russia', 'team2': 'Korea Republic', 'gd': 1},
        {'team1': 'Slovenia', 'team2': 'Canada', 'gd': 1},
        {'team1': 'South Africa', 'team2': 'Spain', 'gd': 1},
        {'team1': 'Sweden', 'team2': 'Portugal', 'gd': -1},
        {'team1': 'Syria', 'team2': 'Oman', 'gd': -1},
        {'team1': 'Tanzania', 'team2': 'Zimbabwe', 'gd': 0},
        {'team1': 'Trinidad and Tobago', 'team2': 'Jamaica', 'gd': 2},
        {'team1': 'Turkey', 'team2': 'Belarus', 'gd': 1},
        {'team1': 'United Arab Emirates', 'team2': 'Vietnam', 'gd': 5},
        {'team1': 'New Zealand', 'team2': 'Mexico', 'gd': -2},
        {'team1': 'Uruguay', 'team2': 'Jordan', 'gd': 0},
        {'team1': 'Singapore', 'team2': 'Cambodia', 'gd': 1},
        {'team1': 'Kenya', 'team2': 'Ethiopia', 'gd': 0},
        {'team1': 'Seychelles', 'team2': 'Maldives', 'gd': 2},
        {'team1': 'Zanzibar', 'team2': 'South Sudan', 'gd': 1},
        {'team1': 'Burundi', 'team2': 'Somalia', 'gd': 2},
        {'team1': 'Tanzania', 'team2': 'Zambia', 'gd': 0},
        {'team1': 'Seychelles', 'team2': 'Maldives', 'gd': 1},
        {'team1': 'Sudan', 'team2': 'Eritrea', 'gd': 3},
        {'team1': 'Uganda', 'team2': 'Rwanda', 'gd': 1},
        {'team1': 'Dominica', 'team2': 'St Lucia', 'gd': -1},
        {'team1': 'Ethiopia', 'team2': 'Zanzibar', 'gd': 2},
        {'team1': 'South Sudan', 'team2': 'Kenya', 'gd': -2},
        {'team1': 'Dominica', 'team2': 'St Lucia', 'gd': 1},
        {'team1': 'Somalia', 'team2': 'Tanzania', 'gd': -1},

    ]
